#!/usr/bin/env racket
#lang racket

(require racket/cmdline
         racket/file
         racket/runtime-path
         racket/string
         "library-manifest.rkt")

(define-runtime-path root-dir "../..")
(define-runtime-path default-out-dir "build/native")
(define-runtime-path default-prefix "build/install")
(define-runtime-path default-manifest "manifest.rktd")

(define cli-source (build-path root-dir "cli" "as.rkt"))

(define (arg->string value)
  (cond
    [(path? value) (path->string value)]
    [else (format "~a" value)]))

(define (run-command exe . args)
  (define argv (map arg->string args))
  (printf "+ ~a ~a\n" (arg->string exe) (string-join argv " "))
  (unless (apply system* exe argv)
    (error 'build.rkt "command failed: ~a ~a" exe argv)))

(define (native-macos-aarch64?)
  (and (eq? (system-type 'os) 'macosx)
       (eq? (system-type 'arch) 'aarch64)))

(define (require-tool name)
  (or (find-executable-path name)
      (error 'build.rkt "required tool not found: ~a" name)))

(define (compile-asmp-source racket-exe name source asm-dir object-dir)
  (define asm-path (build-path asm-dir (format "~a.s" name)))
  (define object-path (build-path object-dir (format "~a.o" name)))
  (run-command racket-exe
               cli-source
               "--gnu-input"
               "--apple"
               "--elim"
               "-o"
               asm-path
               source)
  (values asm-path object-path))

(define (compile-object clang asm-path object-path)
  (run-command clang "-c" asm-path "-o" object-path)
  object-path)

(define (write-pkg-config prefix pc-path)
  (call-with-output-file pc-path
    (lambda (out)
      (fprintf out "prefix=~a\n" prefix)
      (display "includedir=${prefix}/include\n" out)
      (display "libdir=${prefix}/lib\n\n" out)
      (display "Name: asmp-zstd\n" out)
      (display "Description: AArch64 zstd frame encoder generated by asmp\n" out)
      (display "Version: 0.1.0\n" out)
      (display "Cflags: -I${includedir}\n" out)
      (display "Libs: -L${libdir} -lasmp_zstd\n" out))
    #:exists 'truncate/replace))

(define (install-native-library library-path header-path prefix)
  (define include-dir (build-path prefix "include"))
  (define lib-dir (build-path prefix "lib"))
  (define pc-dir (build-path lib-dir "pkgconfig"))
  (make-directory* include-dir)
  (make-directory* lib-dir)
  (make-directory* pc-dir)
  (define installed-header (build-path include-dir "asmp_zstd.h"))
  (define installed-library (build-path lib-dir "libasmp_zstd.a"))
  (copy-file header-path installed-header #t)
  (copy-file library-path installed-library #t)
  (define pc-path (build-path pc-dir "asmp-zstd.pc"))
  (write-pkg-config prefix pc-path)
  (printf "installed library: ~a\n" installed-library)
  (printf "installed header: ~a\n" installed-header)
  (printf "installed pkg-config: ~a\n" pc-path)
  (values installed-library installed-header pc-path))

(define (build-native-library manifest-path out-dir library-name-override)
  (unless (native-macos-aarch64?)
    (error 'build.rkt
           "native library build is currently macOS arm64 only; host is ~a/~a"
           (system-type 'os)
           (system-type 'arch)))
  (define manifest (read-library-manifest manifest-path))
  (define library-name (manifest-library-name manifest library-name-override))
  (define racket-exe (require-tool "racket"))
  (define clang (require-tool "clang"))
  (define ar (require-tool "ar"))
  (define ranlib (require-tool "ranlib"))

  (define asm-dir (build-path out-dir "asm"))
  (define object-dir (build-path out-dir "obj"))
  (define include-dir (build-path out-dir "include"))
  (make-directory* asm-dir)
  (make-directory* object-dir)
  (make-directory* include-dir)

  (define object-paths
    (for/list ([source-entry (in-list (manifest-sources manifest))])
      (define name (car source-entry))
      (define source (cdr source-entry))
      (define-values (asm-path object-path)
        (compile-asmp-source racket-exe name source asm-dir object-dir))
      (compile-object clang asm-path object-path)))

  (define library-path (build-path out-dir library-name))
  (when (file-exists? library-path)
    (delete-file library-path))
  (apply run-command ar "rcs" library-path object-paths)
  (run-command ranlib library-path)

  (define installed-header (build-path include-dir "asmp_zstd.h"))
  (write-library-header manifest installed-header)

  (printf "built static library: ~a\n" library-path)
  (printf "installed header: ~a\n" installed-header)
  (values library-path installed-header))

(module+ main
  (define out-dir default-out-dir)
  (define prefix default-prefix)
  (define manifest-path default-manifest)
  (define library-name-override #f)
  (define install? #f)
  (command-line
   #:program "build.rkt"
   #:once-each
   [("--manifest") path "Library manifest to build"
                   (set! manifest-path path)]
   [("--out-dir") path "Output directory for asm, objects, library, and header"
                  (set! out-dir path)]
   [("--prefix") path "Install prefix for --install; defaults to build/install"
                (set! prefix path)]
   [("--install") "Install header, static library, and pkg-config file under prefix"
                  (set! install? #t)]
   [("--library-name") name "Static library filename"
                       (set! library-name-override name)]
   #:args ()
   (call-with-values
    (lambda () (build-native-library manifest-path out-dir library-name-override))
    (lambda (library-path header-path)
      (when install?
        (call-with-values
         (lambda () (install-native-library library-path header-path prefix))
         (lambda results (void))))))))
