("Conditional branch (immediate)" ("branches" "conditional")
  ((_ 7) (o1 1) (imm19 19) (o0 1) (cond 4)))
("Exception generation" ("exception generating" "unconditional")
  ((_ 8) (opc 3) (imm16 16) (op2 3) (LL 2)))
("System" ("system instructions")
  ((_ 10) (L 1) (op0 2) (op1 3) (CRn 4) (CRm 4) (op2 3) (Rt 5)))
("Unconditional branch (register)" ("branches" "unconditional")
  ((_ 7) (opc 4) (op2 5) (op3 6) (Rn 5) (Rm 5)))
("Unconditional branch (immediate)" ("branches" "unconditional")
  ((op 1) (_ 5) (imm26 26)))
("Compare and branch (immediate)" ("branches" "conditional")
  ((sf 1) (_ 6) (op 1) (imm19 19) (Rt 5)))
("Test and branch (immediate)" ("branches" "conditional")
  ((b5 1) (_ 6) (op 1) (b40 5) (imm14 14) (Rt 5)))
