("Data-processing (2 source)" ("data processing" "2 source")
  ((sf 1) (_ 1) (S 1) (_ 8) (Rm 5) (opcode 6) (Rn 5) (Rd 5)))
("Data-processing (1 source)" ("data processing" "1 source")
  ((sf 1) (_ 1) (S 1) (_ 8) (opcode2 5) (opcode 6) (Rn 5) (Rd 5)))
("Logical (shifted register)" ("data processing" "logical")
  ((sf 1) (opc 2) (_ 5) (shift 2) (N 1) (Rm 5) (imm6 6) (Rn 5) (Rd 5)))
("Add/subtract (shifted register)" ("data processing" "add/subtract")
  ((sf 1) (op 1) (S 1) (_ 5) (shift 2) (_ 1) (Rm 5) (imm6 6) (Rn 5) (Rd 5)))
("Add/subtract (extended register)" ("data processing" "add/subtract")
  ((sf 1) (op 1) (S 1) (_ 5) (opt 2) (_ 1) (Rm 5) (option 3) (imm 3) (Rn 5) (Rd 5)))
("Add/subtract (with carry)" ("data processing" "add/subtract" "carry")
  ((sf 1) (op 1) (S 1) (_ 8) (Rm 5) (opcode2 6) (Rn 5) (Rd 5)))
("Conditional compare (register)" ("data processing" "conditional")
  ((sf 1) (op 1) (S 1) (_ 8) (Rm 5) (cond 4) (_ 1) (o2 1) (Rn 5) (o3 1) (nzcv 4)))
("Conditional compare (immediate)" ("data processing" "conditional" "immediate")
  ((sf 1) (op 1) (S 1) (_ 8) (imm5 5) (cond 4) (_ 1) (o2 1) (Rn 5) (o3 1) (nzcv 4)))
("Conditional select" ("data processing" "conditional")
  ((sf 1) (op 1) (S 1) (_ 8) (Rm 5) (cond 4) (op2 2) (Rn 5) (Rd 5)))
("Data-processing (3 source)" ("data processing" "3 source")
  ((sf 1) (op54 2) (_ 5) (op31 3) (Rm 5) (o0 1) (Ra 5) (Rn 5) (Rd 5)))
