("Cryptographic AES" ("data processing" "crypto" "aes")
  ((_ 8) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Cryptographic three-register SHA" ("data processing" "crypto" "sha")
  ((_ 8) (size 2) (_ 1) (Rm 5) (_ 1) (opcode 3) (_ 2) (Rn 5) (Rd 5)))
("Cryptographic two-register SHA" ("data processing" "crypto" "sha")
  ((_ 8) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD scalar copy" ("data processing" "simd" "advanced simd")
  ((_ 2) (op 1) (_ 8) (imm5 5) (_ 1) (imm4 4) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD scalar three same FP16" ("data processing" "simd" "advanced simd")
  ((_ 2) (op 1) (_ 5) (a 1) (_ 2) (Rm 5) (_ 2) (opcode 3) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD scalar two-register miscellaneous FP16" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (a 1) (_ 6) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD scalar three same extra" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (_ 1) (opcode 4) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD scalar two-register miscellaneous" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD scalar pairwise" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD scalar three different" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (opcode 4) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD scalar three same" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (opcode 5) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD scalar shift by immediate" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 6) (immh 4) (immb 3) (opcode 5) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD scalar x indexed element" ("data processing" "simd" "advanced simd")
  ((_ 2) (U 1) (_ 5) (size 2) (L 1) (M 1) (Rm 4) (opcode 4) (H 1) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD table lookup" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (_ 6) (op2 2) (_ 1) (Rm 5) (_ 1) (len 2) (op 1) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD permute" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (_ 6) (size 2) (_ 1) (Rm 5) (_ 1) (opcode 3) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD extract" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (_ 6) (op2 2) (_ 1) (Rm 5) (_ 1) (imm4 4) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD copy" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (op 1) (_ 8) (imm5 5) (_ 1) (imm4 4) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD three same (FP16)" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (a 1) (_ 2) (Rm 5) (_ 2) (opcode 3) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD two-register miscellaneous (FP16)" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (a 1) (_ 6) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD three same extra" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (_ 1) (opcode 4) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD two-register miscellaneous" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD across lanes" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (_ 5) (opcode 5) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD three different" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (opcode 4) (_ 2) (Rn 5) (Rd 5)))
("Advanced SIMD three same" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (_ 1) (Rm 5) (opcode 5) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD modified immediate" ("data processing" "simd" "advanced simd" "immediate")
  ((_ 1) (Q 1) (op 1) (_ 10) (a 1) (b 1) (c 1) (cmode 4) (o2 1) (_ 1)
  (d 1) (e 1) (f 1) (g 1) (h 1) (Rd 5)))
("Advanced SIMD shift by immediate" ("data processing" "simd" "advanced simd" "immediate")
  ((_ 1) (Q 1) (U 1) (_ 6) (immh 4) (immb 3) (opcode 5) (_ 1) (Rn 5) (Rd 5)))
("Advanced SIMD vector x indexed element" ("data processing" "simd" "advanced simd")
  ((_ 1) (Q 1) (U 1) (_ 5) (size 2) (L 1) (M 1) (Rm 4) (opcode 4) (H 1) (_ 1) (Rn 5) (Rd 5)))
("Cryptographic three-register, imm2" ("data processing" "crypto")
  ((_ 11) (Rm 5) (_ 2) (imm2 2) (opcode 2) (Rn 5) (Rd 5)))
("Cryptographic three-register SHA 512" ("data processing" "crypto" "sha")
  ((_ 11) (Rm 5) (_ 1) (O 1) (_ 2) (opcode 2) (Rn 5) (Rd 5)))
("Cryptographic four-register" ("data processing" "crypto")
  ((_ 9) (Op0 2) (Rm 5) (_ 1) (Ra 5) (Rn 5) (Rd 5)))
("Cryptographic two-register SHA 512" ("data processing" "crypto" "sha")
  ((_ 20) (opcode 2) (Rn 5) (Rd 5)))
("Conversion between floating-point and fixed-point"
  ("data processing" "floating-point" "conversion")
  ((sf 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (rmode 2) (opcode 3) (scale 6)
  (Rn 5) (Rd 5)))
("Conversion between floating-point and integer"
  ("data processing" "floating-point" "conversion")
  ((sf 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (rmode 2) (opcode 3) (_ 6)
  (Rn 5) (Rd 5)))
("Floating-point data-processing (1 source)" ("data processing" "1 source" "floating-point")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (opcode 6) (_ 5) (Rn 5) (Rd 5))) 
("Floating-point compare" ("data processing" "floating-point")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (Rm 5) (op 2) (_ 4) (Rn 5) (opcode2 5)))
("Floating-point immediate" ("data processing" "floating-point" "immediate")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (imm8 8) (_ 3) (imm5 5) (Rd 5)))
("Floating-point conditional compare" ("data processing" "floating-point" "conditional")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (Rm 5) (cond 4) (_ 2) (Rn 5) (op 1) (nzcv 4)))
("Floating-point data-processing (2 source)" ("data processing" "2 source" "floating-point")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (Rm 5) (opcode 4) (_ 2) (Rn 5) (Rd 5))) 
("Floating-point conditional select" ("data processing" "floating-point" "conditional")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (_ 1) (Rm 5) (cond 4) (_ 2) (Rn 5) (Rd 5))) 
("Floating-point data-processing (3 source)" ("data processing" "floating-point" "3 source")
  ((M 1) (_ 1) (S 1) (_ 5) (type 2) (o1 1) (Rm 5) (o0 1) (Ra 5) (Rn 5) (Rd 5))) 
