("PC-rel. addressing" ("data processing" "immediate")
  ((o 1) (immlo 2) (_ 5) (immhi 19) (rd 5)))
("Add/subtract (immediate)" ("data processing" "immediate" "add" "subtract")
  ((sf 1) (op 1) (S 1) (_ 5) (shift 2) (imm12 12) (Rn 5) (Rd 5)))
("Logical (immediate)" ("data processing" "immediate" "logical")
  ((sf 1) (opc 2) (_ 6) (N 1) (immr 6) (imms 6) (Rn 5) (Rd 5)))
("Move wide (immediate)" ("data processing" "immediate" "move" "wide")
  ((sf 1) (opc 2) (_ 6) (hw 2) (imm16 16) (Rd 5)))
("Bitfield" ("data processing" "immediate" "bitfield")
  ((sf 1) (opc 2) (_ 6) (N 1) (immr 6) (imms 6) (Rn 5) (Rd 5)))
("Extract" ("data processing" "immediate" "extract")
  ((sf 1) (op21 2) (_ 6) (N 1) (o0 1) (Rm 5) (imms 6) (Rn 5) (Rd 5)))
