("Loads and Stores" ("mem")
  ((op0 1) (_ 1) (op1 2) (_ 1) (op2 1) (_ 1) (op3 2) (_ 1)
  (op4 6) (_ 4) (op5 2) (_ 10)))
("Advanced SIMD load/store multiple structures" ("loads" "stores" "advanced simd")
  ((_ 1) (Q 1) (_ 7) (L 1) (_ 6) (opcode 4) (size 2) (Rn 5) (Rt 5)))
("Advanced SIMD load/store multiple structures (post-indexed)"
  ("mem" "advanced simd" "post-indexed")
  ((_ 1) (Q 1) (_ 7) (L 1) (_ 1) (Rm 5) (opcode 4) (size 2) (Rn 5) (Rt 5)))
("Advanced SIMD load/store single structure"
  ("mem" "advanced simd")
  ((_ 1) (Q 1) (_ 7) (L 1) (R 1) (_ 5) (opcode 3) (S 1) (size 2) (Rn 5) (Rt 5)))
("Advanced SIMD load/store single structure (post-indexed)"
  ("mem" "advanced simd" "post-indexed")
  ((_ 1) (Q 1) (_ 7) (L 1) (R 1) (Rm 5) (opcode 3) (S 1) (size 2) (Rn 5) (Rt 5)))
("Load/store exclusive" ("mem")
  ((size 2) (_ 6) (o2 1) (L 1) (o1 1) (Rs 5) (o0 1) (Rt2 5) (Rn 5) (Rt 5)))
("Load register (literal)" ("mem")
  ((opc 2) (_ 3) (V 1) (_ 2) (imm19 19) (Rt 5)))
("Load/store no-allocate pair (offset)" ("mem" "pair")
  ((opc 2) (_ 3) (V 1) (_ 3) (L 1) (imm7 7) (Rt2 5) (Rn 5) (Rt 5)))
("Load/store register pair (post-indexed)" ("mem" "pair" "post-indexed")
  ((opc 2) (_ 3) (V 1) (_ 3) (L 1) (imm7 7) (Rt2 5) (Rn 5) (Rt 5)))
("Load/store register pair (offset)" ("mem" "pair")
  ((opc 2) (_ 3) (V 1) (_ 3) (L 1) (imm7 7) (Rt2 5) (Rn 5) (Rt 5)))
("Load/store register pair (pre-indexed)" ("mem" "pair" "pre-indexed")
  ((opc 2) (_ 3) (V 1) (_ 3) (L 1) (imm7 7) (Rt2 5) (Rn 5) (Rt 5)))
("Load/store register (unscaled immediate)" ("mem" "immediate" "unscaled")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (_ 1) (imm9 9) (_ 2) (Rn 5) (Rt 5)))
("Load/store register (immediate post-indexed)" ("mem" "immediate")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (_ 1) (imm9 9) (_ 2) (Rn 5) (Rt 5)))
("Load/store register (unprivileged)" ("mem" "unprivileged")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (_ 1) (imm9 9) (_ 2) (Rn 5) (Rt 5)))
("Load/store register (immediate pre-indexed)" ("mem" "immediate" "pre-indexed")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (_ 1) (imm9 9) (_ 2) (Rn 5) (Rt 5)))
("Atomic memory operations" ("mem" "atomic")
  ((size 2) (_ 3) (V 1) (_ 2) (A 1) (R 1) (_ 1) (Rs 5) (o3 1) (opc 3) (_ 2) (Rn 5) (Rt 5)))
("Load/store register (register offset)" ("mem")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (_ 1) (Rm 5) (option 3) (S 1) (_ 2) (Rn 5) (Rt 5)))
("Load/store register (pac)" ("mem" "pac")
  ((size 2) (_ 3) (V 1) (_ 2) (M 1) (S 1) (_ 1) (imm9 9) (W 1) (_ 1) (Rn 5) (Rt 5)))
("Load/store register (unsigned immediate)" ("mem" "immediate")
  ((size 2) (_ 3) (V 1) (_ 2) (opc 2) (imm12 12) (Rn 5) (Rt 5)))
