((name . pvector-runtime-boundary)
 (format-version . 2)
 (status . runtime-paper-finger-tree-baseline)
 (design . "pvector-runtime-native-design.md")
 (public-module . racket/pvector)
 (runtime-adapter-module . racket/private/pvector-runtime-adapter)
 (current-racket-backend-module . racket/private/pvector)
 (runtime-candidate-file . "racket/src/cs/rumble/pvector.ss")

 (current-default
  . ((adapter-backend . (finger core))
     (chunked-runtime-status . removed-from-current-boundary)
     (core-available?-meaning . "true only after a no-chunk runtime core with large measured nodes is available")))

 (measure
  . ((mode . fixed-length)
     (unit . 0)
     (leaf . element-count)
     (node . subtree-length)
     (combine . +)
     (note . "The pvector/list-replacement measure is element count only; no generic monoid measure is exposed.")))

 (target-representations
  . ((empty
      . ((allocation . singleton)
         (tree . none)
         (chunk-cache . none)))
     (single
      . ((sizes . "1")
         (allocation . "one runtime object")
         (tree . none)
         (chunk-cache . none)))
     (deep-finger
      . ((sizes . "2..")
         (shape . "paper-style size-measured finger tree")
         (digits . "1..4 direct elements or child nodes")
         (nodes . "node2/node3 with cached element count")
         (chunked-leaves . none)
         (chunk-index-vector . none)
         (ref-cache . none)
         (vector-payload . none)))))

 (compatibility-views
  . ((pvector->chunk-vector
      . ((status . compatibility-only)
         (internal-representation . #f)
         (cache . none)
         (runtime-primitive . absent)
         (note . "The adapter may materialize immutable vector pieces for old low-level callers; callers must not rely on shape.")))
     (pvector->chunk-vector/shared
      . ((status . compatibility-only)
         (internal-representation . #f)
         (runtime-primitive . absent)
         (cache . none)))))

 (runtime-adapter
  . ((file . "racket/collects/racket/private/pvector-runtime-adapter.rkt")
     (fallback-module . "racket/collects/racket/private/pvector.rkt")
     (disabled-core-reason . "compiled core is disabled unless it reports the no-chunk shape")
     (probe-functions . (pvector-runtime-adapter-backend
                         pvector-runtime-adapter-core-available?))
     (fresh-vector-primitive . core-fresh-vector->pvector)
     (expected-default-backend . (finger core))))

 (acceptance
  . ((correctness
      . ("./racket/bin/racket -y pkgs/racket-test/tests/racket/pvector-runtime-adapter.rkt"
         "./racket/bin/racket -y pkgs/racket-test/tests/racket/pvector.rkt"
         "./racket/bin/racket -y pkgs/racket-test/tests/generic/stream.rkt"))
     (no-chunk-baseline
      . ((adapter-backend . (finger core))
         (shape-stats-backend . (finger core))
         (chunk-index-vectors . 0)
         (chunk-constructor-primitives . absent)
         (chunk-view-primitives . absent)
         (hot-sequence-path . vector-snapshot-no-chunk-view)
         (sequence-cursor-primitives . absent)
         (fresh-vector-construction . no-freeze-copy)
         (fresh-result-materialization . no-freeze-copy)
         (deep-digit-lengths . "1..4")
         (core-endpoint-access . direct-no-general-ref)
         (core-vector-length-1..4-construction . direct-single-deep4)
         (core-list-length-1..4-construction . direct-single-deep4-no-temp-vector)
         (core-make-length-2..4 . direct-deep2-deep4-no-temp-vector)
         (core-linear-traversal . map-for-each-list)
         (core-list-conversion . direct-no-vector-snapshot)
         (public-equal/hash . direct-no-chunk-vector-view)
         (public-match-tail-list . direct-no-chunk-lookup)
         (core-range-operations . checked-once-unchecked-range-helper)
         (core-copy-range-check . single-length-read)
         (core-node-ref/set-entry . direct-recursive-no-entry-helper)
         (core-node-nonleaf-measure . direct-child-node-measure-no-level-branch)
         (core-node-leaf-ref/set . direct-field-access-no-entry-helper)
         (core-node-leaf-construction . fixed-measure-direct-record-constructor)
         (core-node-traversal-entry . top-level-helper-no-local-closure)
         (core-node-nonleaf-traversal-entry . direct-recursive-no-level-branch)
         (core-node-leaf-traversal . direct-field-range-no-entry-measure)
         (core-node-full-traversal . direct-recursive-no-range-intersection)
         (core-large-single-append . fixed-size-digit-insert-or-single-digit-bridge)
         (core-large-single-append-known-length . no-length-reprobe)
         (core-large-edge-cons . fixed-size-digit-insert-or-full-digit-bridge)
         (core-large-edge-cons-known-length . no-length-reprobe)
         (core-full-digit-bridge . direct-node2-tree-no-temp-vector)
         (core-full-digit-pair-bridge . direct-node3-tree-no-branch-ref)
         (core-shape-specialized-cons/append . no-obsolete-representation-fallback)
         (core-large-copy-edge-digits . direct-digit-slice-share)
         (core-large-copy-edge-helper . top-level-helper-no-local-closure)
         (core-large-copy-known-length . no-length-reprobe)
         (core-vector-copy-range-length-1..4 . direct-mutable-vector-no-loop-set)
         (core-digit-constructors . inline-vector-immutable-no-freeze-copy)
         (core-digit-slice-length-0..4 . direct-immutable-vector-no-copy-freeze)
         (core-pvector-range-immutable-length-0..4 . direct-immutable-vector-no-temp-fill)
         (core-pvector-range-immutable-known-length . no-length-reprobe)
         (core-bridge-nodes . direct-node-construction-no-temp-vector)
         (core-bridge-root-measure . fixed-bridge-measure-no-child-measure-read)
         (core-bridge-digit-combos . fixed-length-combos-no-per-slot-branch)
         (core-middle-node-links . direct-node2/node3-no-list-vector)
         (core-next-node-level . exact-output-vector-no-copy)
         (core-aligned-slice-short-pieces . direct-node2/node3-no-list-vector)
         (core-aligned-slice-leaf . fixed-case-no-piece-list-or-entry-measure)
         (core-aligned-slice-piece-helper . top-level-helper-no-local-closure-set)
         (core-aligned-slice-nonleaf-entry . direct-child-node-measure-no-level-branch)
         (core-digit-set . direct-fixed-size-immutable-vector)
         (core-digit-insert/delete . direct-fixed-size-immutable-vector)
         (core-large-set-known-length . no-length-reprobe)
         (core-large-set-compare . fused-no-pre-ref)
         (core-large-set-lazy-fields . same-value-return-before-opposite-edge-read)
         (core-insert/delete-top-level-fallback . shape-specialized-direct-dispatch-no-vector-materialization)
         (core-large-insert/delete-known-length . no-length-reprobe)
         (core-large-insert-lazy-fields . prefix-insert-before-suffix-start-computation)
         (core-large-delete-lazy-fields . prefix-delete-before-suffix-start-computation)
         (core-middle-insert/delete-composition . unchecked-copy-after-single-check)
         (core-middle-insert-singleton . cons-right-no-singleton-append)
         (core-middle-insert/delete-known-length-append . no-length-reprobe)
         (core-pop-operations . checked-once-unchecked-range-helper)
         (core-pop-endpoints . direct-view-no-general-ref)
         (core-pop-edge-digits . direct-large-finger-digit-shrink-no-range-copy)
         (core-pop-edge-known-length . no-length-reprobe)
         (core-pop-edge-view-rest . shared-edge-read-no-duplicate-prefix/suffix-ref)
         (core-delete-endpoints . direct-copy-no-empty-append)
         (core-delete-edge-digits . direct-large-finger-digit-shrink-no-range-copy)
         (core-delete-edge-view-rest . shared-edge-read-no-pre-ref)
         (core-delete-middle-fallback . no-edge-reprobe-after-fused-edge-view)
         (core-short-set . direct-single-deep2-no-digit-copy)
         (core-short-pop/delete . direct-empty-single-no-copy-vector)
         (core-short-construction-3/4 . direct-deep3/deep4-no-temp-vector)
         (core-short-copy . direct-single-deep4-no-temp-vector)
         (core-large-short-copy . direct-digit-or-known-pieces-no-generic-ref)
         (core-short-copy-endpoints . direct-digit-no-indexed-descent)
         (core-short-range-endpoints . first-last-edge-check-only)
         (core-large-short-immutable-range . direct-digit-or-known-pieces-no-generic-ref)
         (core-copy-edge-one . direct-large-finger-digit-shrink-no-range-copy)
         (core-copy-edge-trim . direct-large-finger-multi-edge-shrink-no-range-copy)
         (core-copy-edge-one-known-length . no-length-reprobe)
         (core-copy-fallback-fill-known-length . no-length-reprobe)
         (core-range-endpoints . direct-empty-self-no-copy-helper)
         (core-checked-ref-endpoints . direct-endpoint-no-indexed-descent)
         (core-indexed-ref-known-length . no-length-reprobe)
         (core-large-ref-prefix-hit . lazy-suffix-read)
         (core-set-endpoint-compare . direct-endpoint-no-indexed-descent)
         (core-split-endpoints . direct-empty-self-no-copy-helper)
         (core-split-at-edge-one . shared-edge-view-rest-no-double-copy)
         (core-split-at-edge-interior . shared-edge-digits-no-double-copy)
         (core-split-edge-lazy-fields . prefix-branch-before-suffix-start-computation)
         (core-split-at-edge-lazy-fields . prefix-branch-before-suffix-start-computation)
         (core-split-edge-view . shared-edge-read-no-pre-ref-or-side-copy)
         (core-split/delete-selected-endpoints . direct-endpoint-no-indexed-descent)
         (core-short-list/vector-materialization . direct-length-0..4-no-known-pieces)
         (core-short-deep-materialization . known-pieces-known-suffix-start-no-field-reprobe-or-ref-helper)
         (core-pvector->vector-length-1..4 . direct-mutable-vector-no-make/set)
         (core-map-length-1..4 . direct-single-deep4-no-temp-vector)
         (core-map/for-each-short-deep . direct-digit-or-node2-leaf-no-known-pieces)
         (core-map-large-fill . direct-range-map-no-for-each-closure)
         (core-vector-segment-traversal . shared-top-level-helpers-no-local-closure-set)
         (core-large-traversal-known-length . no-length-reprobe)
         (core-large-full-range . direct-prefix-middle-suffix-no-segment-crop)
         (core-large-partial-edge-ranges . direct-prefix/suffix-no-opposite-field-read)
         (core-large-partial-middle-ranges . direct-node-range-no-edge-segment-crop)
         (core-for-each-length-1..4 . direct-endpoint-no-range-traversal)
         (core-small-construction . direct-empty-single-deep4)
         (public-arity-1..4-construction . direct-single-deep4-no-temp-vector)
         (public-list/vector-length-1..4-construction . direct-single-deep4-no-input-vector-copy)
         (public-literal-range-length-1..4 . direct-single-deep4-no-temp-vector)
         (adapter-range-length-1..4 . direct-single-deep4-no-temp-vector)
         (public-list/vector-materialization-length-1..4 . direct-endpoint-no-runtime-length-check)
         (public-map-length-1 . direct-core-map-no-temporary-vector)
         (public/adapter-make-length-5+ . runtime-core-make-no-vector-immutable)
         (ref-cache? . #f)
         (core-large-finger
          . ((payload-vectors . 0)
             (digit-vectors . 2)
             (prefix-length . "1..4")
             (suffix-length . "1..4")
             (finger-nodes . positive)))))
     (performance
      . ((release-gate . "./racket/bin/racket -y pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/gate.rkt --performance")
         (smoke-gate . "./racket/bin/racket -y pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/gate.rkt --performance-smoke")
         (workload-script . "pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/list-workload.rkt")
         (spectrum-script . "pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/list-spectrum.rkt")
         (score-script . "pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/list-score.rkt")
         (score-script-output . "detail rows include iterations, real-ms, real-ns/op, live-bytes, generated-result-cost-units, result-cost-units/op, and scores; power-score rows aggregate each power-of-two size; total-score rows aggregate power scores; every row carries score profile, weighting, interface-model, metric columns, and score-method ratio labels")
         (score-profile
          . ((name . academic-clean)
             (baseline . list)
             (speed-weight . 0.7)
             (cost-weight . 0.3)
             (score-direction . higher-is-better)
             (speed-metric . real-ns/op)
             (cost-model . academic-result-cost)
             (cost-metric . academic-result-cost-units/op)
             (speed-ratio . baseline/target)
             (cost-ratio . zero-aware-add1-baseline/target)
             (size-weighting . equal-per-power-size)
             (operation-weighting . equal-per-operation-within-size)
             (benchmark-layer . direct-interface-no-extra-adapter)))
         (latest-smoke
          . ((date . "2026-06-14")
             (status . stale-after-small-flat-removal)
             (known-blockers
              . ("performance must be remeasured with list-score before adding representation optimizations"
                 "paper-style deep-finger baseline is correctness-first and not expected to pass the old flat-tuned smoke thresholds"))))
         (latest-score-smoke
         . ((date . "2026-06-14")
             (command . "./racket/bin/racket -y pkgs/racket-benchmarks/tests/racket/benchmarks/pvector/list-score.rkt --target-ms 3 --m 100 --max-m 100000 --sizes 1,2,4,8,16,64,256 --ops build,sum,append-self,map-add1 --impls list,vector,treelist,pvector,adapter-pvector")
             (status . stale-after-zero-aware-cost-ratio)
             (note . "This score smoke is a broad optimization signal, not an acceptance threshold; it is intentionally not rebaselined by the fresh-vector runtime/internal materialization entry or the later zero-aware cost-ratio tightening.")
             (total-score/list
              . ((list . 1.0)
                 (vector . 1.2505)
                 (treelist . 0.8804)
                 (pvector . 0.5659)
                 (adapter-pvector . 0.5624)))
             (speed-score/list
              . ((list . 1.0)
                 (vector . 1.0260)
                 (treelist . 0.6215)
                 (pvector . 0.3665)
                 (adapter-pvector . 0.3797)))
             (cost-score/list
              . ((list . 1.0)
                 (vector . 1.9841)
                 (treelist . 1.9841)
                 (pvector . 1.5587)
                 (adapter-pvector . 1.4062)))))))
     (next-runtime-gate
      . ("remeasure paper-style empty/single/deep-finger paths with list-score"
         "only add specialized representations after list-score shows broad benefit, not from a single size/op")))))
