// ============================================================
// 002-frame-litonly.asm - zstd compressed-block literal-only frame
// ============================================================
//
// This is the first compressed-block formatting step for zstd01. It still
// stores every byte as a literal, but emits the zstd compressed-block shape:
//
//   Block_Header(type=Compressed_Block)
//   Literals_Section(type=Raw_Literals_Block)
//   Sequences_Section(Number_of_Sequences = 0)
//
// There is no match finder or FSE bitstream yet. The block payload limit is
// deliberately 65535 bytes so the raw literals header plus the zero-sequence
// byte always stay below zstd's 128 KiB compressed-block content limit.

.function zstd02_bound_inner (
  in: x.src_len,
  out: x.bound
)
entry:
  ubfm x.extra, x.src_len, #12, #63
  add x.bound, x.src_len, x.extra
  add x.bound, x.bound, #64
  ret
.end

.function zstd02_write_u24 (
  inout: x.out,
  in: x.value
)
entry:
  strb w.value, [x.out]
  add x.out, x.out, #1
  ubfm x.tmp, x.value, #8, #63
  strb w.tmp, [x.out]
  add x.out, x.out, #1
  ubfm x.tmp, x.value, #16, #63
  strb w.tmp, [x.out]
  add x.out, x.out, #1
  ret
.end

.function zstd02_write_u16 (
  inout: x.out,
  in: x.value
)
entry:
  strb w.value, [x.out]
  add x.out, x.out, #1
  ubfm x.tmp, x.value, #8, #63
  strb w.tmp, [x.out]
  add x.out, x.out, #1
  ret
.end

.function zstd02_copy_bytes (
  inout: x.out, x.in, x.count
)
entry:
copy_loop:
  cbz x.count, copy_done
  ldrb w.byte, [x.in]
  strb w.byte, [x.out]
  add x.in, x.in, #1
  add x.out, x.out, #1
  sub x.count, x.count, #1
  b copy_loop

copy_done:
  ret
.end

.function zstd02_write_frame_header (
  inout: x.out,
  in: x.src_len
)
entry:
  mov w.byte, #0x28
  strb w.byte, [x.out]
  add x.out, x.out, #1
  mov w.byte, #0xb5
  strb w.byte, [x.out]
  add x.out, x.out, #1
  mov w.byte, #0x2f
  strb w.byte, [x.out]
  add x.out, x.out, #1
  mov w.byte, #0xfd
  strb w.byte, [x.out]
  add x.out, x.out, #1

  // FCS flag=3, single_segment=0. A literal-only compressed block can be
  // larger than its regenerated bytes, so it needs an explicit window.
  mov w.byte, #0xc0
  strb w.byte, [x.out]
  add x.out, x.out, #1

  // Window_Descriptor exponent=7, mantissa=0 => 128 KiB.
  mov w.byte, #0x38
  strb w.byte, [x.out]
  add x.out, x.out, #1

  str x.src_len, [x.out]
  add x.out, x.out, #8
  ret
.end

.function zstd02_write_empty_block (
  inout: x.out
)
entry:
  mov x.header, #1
  .inline zstd02_write_u24 (x.out=x.out, x.value=x.header)
  ret
.end

.function zstd02_lit_header_size (
  in: x.block_len,
  out: x.header_size
)
entry:
  mov x.header_size, #1
  cmp x.block_len, #32
  b.lo size_done
  mov x.header_size, #2
  cmp x.block_len, #4096
  b.lo size_done
  mov x.header_size, #3

size_done:
  ret
.end

.function zstd02_write_litonly_block (
  inout: x.out, x.in,
  in: x.block_len, x.last
)
entry:
  .inline zstd02_lit_header_size (x.block_len=x.block_len, x.header_size=x.lit_header_size)
  add x.content_size, x.block_len, x.lit_header_size
  add x.content_size, x.content_size, #1

  add x.header, x.content_size, x.content_size
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  orr x.header, x.header, #4
  orr x.header, x.header, x.last
  .inline zstd02_write_u24 (x.out=x.out, x.value=x.header)

  cmp x.block_len, #32
  b.hs litonly_header_two_or_three

  // Raw literals, 1-byte header: type=0, size_format=0, size in bits 3..7.
  add x.header, x.block_len, x.block_len
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  strb w.header, [x.out]
  add x.out, x.out, #1
  b litonly_header_done

litonly_header_done:
  mov x.count, x.block_len
  .inline zstd02_copy_bytes (x.out=x.out, x.in=x.in, x.count=x.count)

  // Number_of_Sequences = 0, so the sequence section stops immediately.
  mov w.seq_count, #0
  strb w.seq_count, [x.out]
  add x.out, x.out, #1
  ret

litonly_header_two_or_three:
  cmp x.block_len, #4096
  b.hs litonly_header_three

  // Raw literals, 2-byte header: type=0, size_format=1, size in bits 4..15.
  add x.header, x.block_len, x.block_len
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  add x.header, x.header, #4
  .inline zstd02_write_u16 (x.out=x.out, x.value=x.header)
  b litonly_header_done

litonly_header_three:
  // Raw literals, 3-byte header: type=0, size_format=3, size in bits 4..23.
  add x.header, x.block_len, x.block_len
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  add x.header, x.header, x.header
  add x.header, x.header, #12
  strb w.header, [x.out]
  add x.out, x.out, #1
  ubfm x.header_byte, x.header, #8, #63
  strb w.header_byte, [x.out]
  add x.out, x.out, #1
  ubfm x.header_byte, x.header, #16, #63
  strb w.header_byte, [x.out]
  add x.out, x.out, #1
  b litonly_header_done
.end

.function zstd02_compress_litonly_frame (
  in: x.dst, x.src, x.src_len,
  out: x.written
)
entry:
  mov x.out, x.dst
  mov x.in, x.src
  mov x.remaining, x.src_len
  .inline zstd02_write_frame_header (x.out=x.out, x.src_len=x.src_len)

  cbnz x.remaining, block_loop
  .inline zstd02_write_empty_block (x.out=x.out)
  b frame_done

block_loop:
  movz x.block_max, #0xffff
  cmp x.remaining, x.block_max
  b.ls use_remaining
  mov x.block_len, x.block_max
  b have_block_len

use_remaining:
  mov x.block_len, x.remaining
  b have_block_len

have_block_len:
  cmp x.remaining, x.block_len
  cset x.last, eq
  .inline zstd02_write_litonly_block (x.out=x.out, x.in=x.in, x.block_len=x.block_len, x.last=x.last)
  sub x.remaining, x.remaining, x.block_len
  cbnz x.remaining, block_loop
  b frame_done

frame_done:
  sub x.written, x.out, x.dst
  ret
.end

.function asmp_zstd_compress_litonly_bound export profile=c-aapcs64 (
  in: x.src_len,
  out: x.bound
)
entry:
  .inline zstd02_bound_inner (x.src_len=x.src_len, x.bound=x.bound)
  ret
.end

.function asmp_zstd_compress_litonly_scratch_size export profile=c-aapcs64 (
  out: x.size
)
entry:
  mov x.size, #0
  ret
.end

.function asmp_zstd_compress_litonly_scratch_align export profile=c-aapcs64 (
  out: x.align
)
entry:
  mov x.align, #1
  ret
.end

.function asmp_zstd_compress_litonly export profile=c-aapcs64 (
  in: x.dst, x.dst_cap, x.dst_len, x.src, x.src_len, x.scratch, x.scratch_len,
  out: w.status
)
entry:
  .save all

  cbz x.dst, bad_argument
  cbz x.dst_len, bad_argument
  cbz x.src_len, src_ok
  cbz x.src, bad_argument

src_ok:
  .inline zstd02_bound_inner (x.src_len=x.src_len, x.bound=x.required)
  cmp x.dst_cap, x.required
  b.lo dst_too_small

  .call zstd02_compress_litonly_frame (
    x.dst=x.dst,
    x.src=x.src,
    x.src_len=x.src_len,
    x.written=x.written
  )
  str x.written, [x.dst_len]
  mov w.status, #0
  b done

dst_too_small:
  str xzr, [x.dst_len]
  mov w.status, #1
  b done

bad_argument:
  mov w.status, #3
  b done

done:
  .restore all
  ret
.end
