#lang racket/base

(require racket/list
         (prefix-in adapter: racket/private/pvector-runtime-adapter)
         rackunit)

(define (check-model pv xs)
  (check-true (adapter:pvector? pv))
  (check-equal? (adapter:pvector-length pv) (length xs))
  (check-equal? (adapter:pvector->list pv) xs)
  (check-equal? (vector->list (adapter:pvector->vector pv)) xs)
  (for ([x (in-list xs)]
        [i (in-naturals)])
    (check-equal? (adapter:pvector-ref pv i) x)))

(define (chunk-vector->list chunks)
  (append*
   (for/list ([chunk (in-vector chunks)])
     (vector->list chunk))))

(define (chunk-vector-lengths chunks)
  (for/list ([chunk (in-vector chunks)])
    (vector-length chunk)))

(test-case "backend probe"
  (define backend (adapter:pvector-runtime-adapter-backend))
  (check-not-false (memq backend '(core chunked)))
  (check-equal? backend
                (if (adapter:pvector-runtime-adapter-core-available?)
                    'core
                    'chunked)))

(test-case "adapter operations"
  (define xs (range 130))
  (define pv (adapter:list->pvector xs))
  (check-model (adapter:pvector 1 2 3) '(1 2 3))
  (check-model (adapter:pvector 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16)
               (range 17))
  (check-model (apply adapter:pvector (range 32))
               (range 32))
  (check-model (apply adapter:pvector (range 33))
               (range 33))
  (check-model (apply adapter:pvector (range 64))
               (range 64))
  (check-model (apply adapter:pvector (range 65))
               (range 65))
  (check-model (apply adapter:pvector (range 96))
               (range 96))
  (check-model (apply adapter:pvector (range 112))
               (range 112))
  (check-model (apply adapter:pvector (range 128))
               (range 128))
	  (check-model (adapter:list->pvector (range 32))
	               (range 32))
	  (check-model (adapter:list->pvector (range 33))
	               (range 33))
	  (let* ([elem (box 'uniform-list)]
	         [uniform-list (make-list 130 elem)]
	         [pv (adapter:list->pvector uniform-list)])
	    (check-model pv uniform-list)
	    (check-eq? (vector-ref (adapter:pvector->vector pv) 64) elem)
	    (check-eq? (list-ref (adapter:pvector->list pv) 129) elem))
	  (let* ([elem (box 'mixed-list)]
	         [mixed-list (cons elem (cons 'other (make-list 128 elem)))]
	         [pv (adapter:list->pvector mixed-list)])
	    (check-model pv mixed-list)
	    (check-eq? (vector-ref (adapter:pvector->vector pv) 0) elem)
	    (check-equal? (vector-ref (adapter:pvector->vector pv) 1) 'other)
	    (check-eq? (list-ref (adapter:pvector->list pv) 129) elem))
	  (define small-conversion (adapter:pvector 1 2 3 4 5))
  (define small-conversion-vector (adapter:pvector->vector small-conversion))
  (vector-set! small-conversion-vector 0 'changed)
  (check-equal? (vector->list small-conversion-vector) '(changed 2 3 4 5))
  (check-model small-conversion '(1 2 3 4 5))
  (check-model pv xs)
  (check-model (adapter:vector->pvector (list->vector xs)) xs)
  (define immutable-vector-pv
    (adapter:vector->pvector
     (vector->immutable-vector (list->vector xs))))
  (check-model immutable-vector-pv xs)
  (check-equal? (chunk-vector->list
                 (adapter:pvector->chunk-vector/shared immutable-vector-pv))
                xs)
  (check-equal? (for/list ([x (adapter:in-pvector immutable-vector-pv)]) x)
                xs)
  (check-equal? (for/list ([x (adapter:in-pvector-reverse immutable-vector-pv)]) x)
                (reverse xs))
  (check-model (adapter:pvector-map immutable-vector-pv add1)
               (map add1 xs))
  (let ([seen null])
    (adapter:pvector-for-each immutable-vector-pv
                              (lambda (x) (set! seen (cons x seen))))
    (check-equal? (reverse seen) xs))
  (let* ([src (vector 'a 'b 'c)]
         [pv (adapter:vector->pvector src)])
    (vector-set! src 0 'changed)
    (check-model pv '(a b c)))
  (let* ([elem (box 'uniform-vector)]
         [src (make-vector 130 elem)]
         [pv (adapter:vector->pvector src)])
    (vector-set! src 64 'changed)
    (check-model pv (make-list 130 elem))
    (check-eq? (vector-ref (adapter:pvector->vector pv) 64) elem)
    (check-eq? (list-ref (adapter:pvector->list pv) 129) elem)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (define chunks (adapter:pvector->chunk-vector/shared pv))
      (check-true (eq? (vector-ref chunks 0) (vector-ref chunks 1)))))
  (check-model (adapter:sequence->pvector (in-range 130)) xs)
  (check-model (adapter:sequence->pvector (in-range 0 130 1)) xs)
  (check-model (adapter:sequence->pvector (in-range 1 5)) '(1 2 3 4))
  (check-model (adapter:sequence->pvector (in-range 0 8 2)) '(0 2 4 6))
  (check-model (adapter:sequence->pvector 130) xs)
  (check-true (eq? (adapter:list->pvector null)
                   (adapter:pvector-empty)))
  (check-true (eq? (adapter:vector->pvector #())
                   (adapter:pvector-empty)))
  (check-true (eq? (adapter:sequence->pvector 0)
                   (adapter:pvector-empty)))
  (check-model (adapter:make-pvector 5 'x) '(x x x x x))
  (check-model (adapter:make-pvector 32 'x)
               '(x x x x x x x x x x x x x x x x
                 x x x x x x x x x x x x x x x x))
  (check-model (adapter:make-pvector 64 'x)
               (make-list 64 'x))
  (check-model (adapter:make-pvector 65 'x)
               (make-list 65 'x))
  (let* ([elem (box 'x)]
         [made (adapter:make-pvector 130 elem)]
         [made* (adapter:pvector-set made 64 'changed)]
         [made-mid (adapter:pvector-copy made 1 129)]
         [made*-mid (adapter:pvector-copy made* 1 129)]
         [made-prefix (adapter:pvector-take made 100)]
         [made-suffix (adapter:pvector-drop made 30)]
         [made*-prefix (adapter:pvector-take made* 100)]
         [made*-suffix (adapter:pvector-drop made* 30)]
         [made-append (adapter:pvector-append made made)]
         [made*-append (adapter:pvector-append made* made)]
         [made-diff-append (adapter:pvector-append
                            made
                            (adapter:make-pvector 130 'other))]
         [made-cons-left (adapter:pvector-cons-left made elem)]
         [made-cons-right (adapter:pvector-cons-right made elem)]
         [made-cons-diff (adapter:pvector-cons-left made 'other)]
         [made-insert-same (adapter:pvector-insert made 65 elem)]
         [made-insert-diff (adapter:pvector-insert made 65 'other)])
    (check-model made (make-list 130 elem))
    (check-eq? (adapter:pvector-ref made 0) elem)
    (check-eq? (adapter:pvector-ref made 64) elem)
    (check-eq? (adapter:pvector-ref made 129) elem)
    (check-eq? (adapter:pvector-ref made* 0) elem)
    (check-equal? (adapter:pvector-ref made* 64) 'changed)
    (check-eq? (adapter:pvector-ref made* 129) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made) 64) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made*) 0) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made*) 64) 'changed)
    (check-eq? (vector-ref (adapter:pvector->vector made*) 129) elem)
    (check-eq? (list-ref (adapter:pvector->list made) 64) elem)
    (check-eq? (list-ref (adapter:pvector->list made*) 0) elem)
    (check-equal? (list-ref (adapter:pvector->list made*) 64) 'changed)
    (check-eq? (list-ref (adapter:pvector->list made*) 129) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-mid) 63) elem)
    (check-eq? (list-ref (adapter:pvector->list made-mid) 63) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made*-mid) 0) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made*-mid) 63) 'changed)
    (check-eq? (list-ref (adapter:pvector->list made*-mid) 127) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-prefix) 99) elem)
    (check-eq? (list-ref (adapter:pvector->list made-suffix) 0) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-suffix) 99) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made*-prefix) 64) 'changed)
    (check-equal? (list-ref (adapter:pvector->list made*-suffix) 34) 'changed)
    (check-eq? (vector-ref (adapter:pvector->vector made-append) 129) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-append) 130) elem)
    (check-eq? (list-ref (adapter:pvector->list made-append) 259) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made*-append) 64) 'changed)
    (check-eq? (list-ref (adapter:pvector->list made*-append) 130) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-diff-append) 129) elem)
    (check-equal? (list-ref (adapter:pvector->list made-diff-append) 130) 'other)
    (check-eq? (vector-ref (adapter:pvector->vector made-cons-left) 0) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-cons-left) 130) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-cons-right) 130) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made-cons-diff) 0) 'other)
    (check-eq? (list-ref (adapter:pvector->list made-cons-diff) 1) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-insert-same) 65) elem)
    (check-eq? (vector-ref (adapter:pvector->vector made-insert-same) 130) elem)
    (check-eq? (list-ref (adapter:pvector->list made-insert-same) 66) elem)
    (check-equal? (vector-ref (adapter:pvector->vector made-insert-diff) 65) 'other)
    (check-eq? (vector-ref (adapter:pvector->vector made-insert-diff) 66) elem)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (let* ([left (adapter:list->pvector (range 128))]
             [right (adapter:list->pvector (range 128 192))]
             [appended (adapter:pvector-append left right)]
             [stats (adapter:pvector-shape-stats appended)])
        (check-model appended (range 192))
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 3))
      (let* ([left (adapter:list->pvector (range 130))]
             [right (adapter:list->pvector (range 130 192))]
             [appended (adapter:pvector-append left right)]
             [stats (adapter:pvector-shape-stats appended)])
        (check-model appended (range 192))
        (check-equal? (adapter:pvector-ref appended 129) 129)
        (check-equal? (adapter:pvector-ref appended 130) 130)
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 2)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 4)
        (check-equal? (hash-ref stats 'append-ref-cache-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'append-ref-cache-left-length #f) 130)
        (check-equal? (hash-ref stats 'append-ref-cache-left-slots #f) 3)
        (check-equal? (hash-ref stats 'append-ref-cache-right-slots #f) 1))
      (let* ([left (adapter:list->pvector (range 5000))]
             [right (adapter:list->pvector (range 5000 10000))]
             [appended (adapter:pvector-append left right)]
             [stats (adapter:pvector-shape-stats appended)])
        (check-model appended (range 10000))
        (check-equal? (adapter:pvector-ref appended 4999) 4999)
        (check-equal? (adapter:pvector-ref appended 5000) 5000)
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 2)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 158)
        (check-equal? (hash-ref stats 'append-ref-cache-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'append-ref-cache-left-length #f) 5000)
        (check-equal? (hash-ref stats 'append-ref-cache-left-slots #f) 79)
        (check-equal? (hash-ref stats 'append-ref-cache-right-slots #f) 79))
      (let* ([base (adapter:list->pvector (range 10000))]
             [left (adapter:pvector-take base 5000)]
             [right (adapter:pvector-drop base 5000)]
             [appended (adapter:pvector-append left right)]
             [stats (adapter:pvector-shape-stats appended)])
        (check-model appended (range 10000))
        (check-equal? (adapter:pvector-ref appended 4999) 4999)
        (check-equal? (adapter:pvector-ref appended 5000) 5000)
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 2)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 158)
        (check-equal? (hash-ref stats 'append-ref-cache-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'append-ref-cache-left-length #f) 5000)
        (check-equal? (hash-ref stats 'append-ref-cache-left-slots #f) 79)
        (check-equal? (hash-ref stats 'append-ref-cache-right-slots #f) 79))
      (let* ([xs (range 10000)]
             [base (adapter:list->pvector xs)])
        (for ([small (in-list (list '(a)
                                    '(a b)
                                    '(a b c)
                                    '(a b c d)))])
          (check-model (adapter:pvector-append (apply adapter:pvector small)
                                               base)
                       (append small xs))
          (check-model (adapter:pvector-append base
                                               (apply adapter:pvector small))
                       (append xs small))))
      (let* ([pv (adapter:list->pvector (range 8192))]
             [taken (adapter:pvector-take pv 4096)]
             [taken-stats (adapter:pvector-shape-stats taken)]
             [dropped (adapter:pvector-drop pv 4096)]
             [dropped-stats (adapter:pvector-shape-stats dropped)]
             [taken-right (adapter:pvector-take-right pv 4096)]
             [taken-right-stats (adapter:pvector-shape-stats taken-right)]
             [dropped-right (adapter:pvector-drop-right pv 4096)]
             [dropped-right-stats (adapter:pvector-shape-stats dropped-right)]
             [dropped-unaligned (adapter:pvector-drop pv 5000)]
             [dropped-unaligned-stats
              (adapter:pvector-shape-stats dropped-unaligned)])
        (check-model taken (range 4096))
        (check-equal? (hash-ref taken-stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref taken-stats 'chunk-index-slots 0) 64)
        (check-model dropped (range 4096 8192))
        (check-equal? (hash-ref dropped-stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref dropped-stats 'chunk-index-slots 0) 64)
        (check-model taken-right (range 4096 8192))
        (check-equal? (hash-ref taken-right-stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref taken-right-stats 'chunk-index-slots 0) 64)
        (check-model dropped-right (range 4096))
        (check-equal? (hash-ref dropped-right-stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref dropped-right-stats 'chunk-index-slots 0) 64)
        (check-model dropped-unaligned (range 5000 8192))
        (check-equal? (adapter:pvector-ref dropped-unaligned 0) 5000)
        (check-equal? (adapter:pvector-ref dropped-unaligned 3191) 8191)
        (check-equal? (hash-ref dropped-unaligned-stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref dropped-unaligned-stats 'chunk-index-slots 0) 50)
        (check-equal? (hash-ref dropped-unaligned-stats
                                'shifted-cache-index-vectors
                                0)
                      1)
        (check-equal? (hash-ref dropped-unaligned-stats
                                'shifted-cache-source-start
                                #f)
                      8)
        (check-equal? (hash-ref dropped-unaligned-stats
                                'shifted-cache-front-length
                                #f)
                      0))
      (let* ([pv (adapter:list->pvector (range 8192))])
        (let-values ([(left right) (adapter:pvector-split-at pv 4096)])
          (let ([left-stats (adapter:pvector-shape-stats left)]
                [right-stats (adapter:pvector-shape-stats right)])
            (check-model left (range 4096))
            (check-equal? (hash-ref left-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'chunk-index-slots 0) 64)
            (check-model right (range 4096 8192))
            (check-equal? (hash-ref right-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'chunk-index-slots 0) 64)))
        (let-values ([(left right) (adapter:pvector-split-at pv 5000)])
          (let ([left-stats (adapter:pvector-shape-stats left)]
                [right-stats (adapter:pvector-shape-stats right)])
            (check-model left (range 5000))
            (check-equal? (adapter:pvector-ref left 4999) 4999)
            (check-equal? (hash-ref left-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'chunk-index-slots 0) 79)
            (check-equal? (hash-ref left-stats 'shifted-cache-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'shifted-cache-source-start #f) 0)
            (check-equal? (hash-ref left-stats 'shifted-cache-front-length #f) 0)
            (check-model right (range 5000 8192))
            (check-equal? (adapter:pvector-ref right 0) 5000)
            (check-equal? (hash-ref right-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'chunk-index-slots 0) 50)
            (check-equal? (hash-ref right-stats 'shifted-cache-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'shifted-cache-source-start #f) 8)
            (check-equal? (hash-ref right-stats 'shifted-cache-front-length #f) 0)))
        (let-values ([(left value right) (adapter:pvector-split pv 4095)])
          (let ([left-stats (adapter:pvector-shape-stats left)]
                [right-stats (adapter:pvector-shape-stats right)])
            (check-model left (range 4095))
            (check-equal? value 4095)
            (check-equal? (hash-ref left-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'chunk-index-slots 0) 64)
            (check-model right (range 4096 8192))
            (check-equal? (hash-ref right-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'chunk-index-slots 0) 64)))
        (let-values ([(left value right) (adapter:pvector-split pv 5000)])
          (let ([left-stats (adapter:pvector-shape-stats left)]
                [right-stats (adapter:pvector-shape-stats right)])
            (check-model left (range 5000))
            (check-equal? value 5000)
            (check-equal? (adapter:pvector-ref left 4999) 4999)
            (check-equal? (hash-ref left-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'chunk-index-slots 0) 79)
            (check-equal? (hash-ref left-stats 'shifted-cache-index-vectors 0) 1)
            (check-equal? (hash-ref left-stats 'shifted-cache-source-start #f) 0)
            (check-equal? (hash-ref left-stats 'shifted-cache-front-length #f) 0)
            (check-model right (range 5001 8192))
            (check-equal? (adapter:pvector-ref right 0) 5001)
            (check-equal? (hash-ref right-stats 'chunk-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'chunk-index-slots 0) 50)
            (check-equal? (hash-ref right-stats 'shifted-cache-index-vectors 0) 1)
            (check-equal? (hash-ref right-stats 'shifted-cache-source-start #f) 9)
            (check-equal? (hash-ref right-stats 'shifted-cache-front-length #f) 0)))))
    (let ([count 0])
      (define mapped
        (adapter:pvector-map made
                             (lambda (value)
                               (set! count (add1 count))
                               value)))
      (check-equal? count 130)
      (check-eq? (vector-ref (adapter:pvector->vector mapped) 64) elem)
      (check-eq? (list-ref (adapter:pvector->list mapped) 129) elem))
    (let ([count 0])
      (define mapped
        (adapter:pvector-map made
                             (lambda (value)
                               (set! count (add1 count))
                               (if (= count 66) 'other value))))
      (check-equal? count 130)
      (check-eq? (vector-ref (adapter:pvector->vector mapped) 64) elem)
      (check-equal? (vector-ref (adapter:pvector->vector mapped) 65) 'other)
      (check-eq? (list-ref (adapter:pvector->list mapped) 66) elem))
    (let-values ([(value rest) (adapter:pvector-pop-left made)])
      (check-eq? value elem)
      (check-eq? (vector-ref (adapter:pvector->vector rest) 0) elem)
      (check-eq? (list-ref (adapter:pvector->list rest) 128) elem))
    (let-values ([(value rest) (adapter:pvector-pop-right made)])
      (check-eq? value elem)
      (check-eq? (vector-ref (adapter:pvector->vector rest) 0) elem)
      (check-eq? (list-ref (adapter:pvector->list rest) 128) elem))
    (let-values ([(value rest) (adapter:pvector-pop-left made*)])
      (check-eq? value elem)
      (check-equal? (vector-ref (adapter:pvector->vector rest) 63) 'changed))
    (let-values ([(rest value) (adapter:pvector-delete made 65)])
      (check-eq? value elem)
      (check-eq? (vector-ref (adapter:pvector->vector rest) 64) elem)
      (check-eq? (vector-ref (adapter:pvector->vector rest) 65) elem)
      (check-eq? (list-ref (adapter:pvector->list rest) 128) elem))
    (let-values ([(rest value) (adapter:pvector-delete made* 64)])
      (check-equal? value 'changed)
      (check-eq? (vector-ref (adapter:pvector->vector rest) 64) elem))
    (let-values ([(left right) (adapter:pvector-split-at made 65)])
      (check-eq? (vector-ref (adapter:pvector->vector left) 64) elem)
      (check-eq? (vector-ref (adapter:pvector->vector right) 0) elem)
      (check-eq? (list-ref (adapter:pvector->list right) 64) elem))
    (let-values ([(left right) (adapter:pvector-split-at made* 65)])
      (check-equal? (vector-ref (adapter:pvector->vector left) 64) 'changed)
      (check-eq? (vector-ref (adapter:pvector->vector right) 0) elem)))
  (let ([seen null])
    (check-model (adapter:pvector-map pv
                                      (lambda (x)
                                        (set! seen (cons x seen))
                                        (add1 x)))
                 (map add1 xs))
    (check-equal? (reverse seen) xs))
  (check-true (adapter:pvector-empty?
               (adapter:pvector-map (adapter:pvector-empty) add1)))
  (check-model (adapter:pvector-map (adapter:pvector-drop pv 3) values)
               (drop xs 3))
  (check-true (eq? pv (adapter:pvector-map pv values)))
  (define mapped-void (adapter:pvector-map pv void))
  (check-equal? (adapter:pvector-length mapped-void) (length xs))
  (for ([v (adapter:in-pvector mapped-void)])
    (check-equal? v (void)))
  (let ([seen null])
    (check-equal? (adapter:pvector-for-each (adapter:pvector 'a 'b 'c)
                                            (lambda (v)
                                              (set! seen (append seen (list v)))))
                  (void))
    (check-equal? seen '(a b c)))
  (check-equal? (adapter:pvector-for-each pv void) (void))
  (check-equal? (adapter:pvector-for-each pv values) (void))
  (check-exn exn:fail?
             (lambda ()
               (adapter:pvector-map (adapter:pvector 1)
                                    (lambda (x) (values x x)))))
  (check-equal? (adapter:pvector-view-left pv) 0)
  (check-equal? (adapter:pvector-view-right pv) 129)
  (check-model (adapter:pvector-set pv 64 'x)
               (append (take xs 64) '(x) (drop xs 65)))
  (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
    (check-true (eq? pv (adapter:pvector-set pv 64 64)))
    (check-false (eq? pv (adapter:pvector-set pv 64 'x))))
  (define-values (middle-delete middle-deleted)
    (adapter:pvector-delete pv 32))
  (check-equal? middle-deleted 32)
  (check-model middle-delete (append (take xs 32) (drop xs 33)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector middle-delete))
                '(63 64 2))
  (define-values (last-chunk-delete last-chunk-deleted)
    (adapter:pvector-delete pv 128))
  (check-equal? last-chunk-deleted 128)
  (check-model last-chunk-delete (append (take xs 128) (drop xs 129)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector last-chunk-delete))
                '(64 64 1))
  (check-model (adapter:pvector-cons-left pv 'left)
               (cons 'left xs))
  (check-model (adapter:pvector-cons-right pv 'right)
               (append xs '(right)))
  (define packed-right
    (for/fold ([pv (adapter:pvector-empty)]) ([i (in-range 9)])
      (adapter:pvector-cons-right pv i)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector packed-right))
                '(8 1))
  (define packed-left
    (for/fold ([pv (adapter:pvector-empty)]) ([i (in-range 9)])
      (adapter:pvector-cons-left pv i)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector packed-left))
                '(1 8))
  (define single-chunk (adapter:pvector 0 1 2 3 4 5 6 7 8 9))
  (define single-set (adapter:pvector-set single-chunk 5 'x))
  (check-model single-set '(0 1 2 3 4 x 6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-set))
                '(10))
  (define-values (single-left single-right)
    (adapter:pvector-split-at single-chunk 5))
  (check-model single-left '(0 1 2 3 4))
  (check-model single-right '(5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-left))
                '(5))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-right))
                '(5))
  (define-values (split-left split-value split-right)
    (adapter:pvector-split single-chunk 5))
  (check-model split-left '(0 1 2 3 4))
  (check-equal? split-value 5)
  (check-model split-right '(6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector split-right))
                '(4))
  (define-values (front-value-left front-value front-value-right)
    (adapter:pvector-split pv 3))
  (check-equal? front-value 3)
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector front-value-left))
                '(3))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector front-value-right))
                '(60 64 2))
  (define-values (back-value-left back-value back-value-right)
    (adapter:pvector-split pv 129))
  (check-equal? back-value 129)
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector back-value-left))
                '(64 64 1))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector back-value-right))
                '())
  (define single-insert (adapter:pvector-insert single-chunk 5 'x))
  (check-model single-insert '(0 1 2 3 4 x 5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-insert))
                '(11))
  (define tail-insert-base (adapter:list->pvector (range 70)))
  (define tail-insert (adapter:pvector-insert tail-insert-base 64 'b))
  (check-model tail-insert (append (range 64) '(b) (range 64 70)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector tail-insert))
                '(64 7))
  (define wide-insert-base (adapter:list->pvector (range 300)))
  (define-values (wide-middle-open wide-middle-deleted)
    (adapter:pvector-delete wide-insert-base 100))
  (check-equal? wide-middle-deleted 100)
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-middle-open))
                '(64 63 64 64 44))
  (define wide-middle-insert (adapter:pvector-insert wide-middle-open 100 'x))
  (check-model wide-middle-insert (append (range 100) '(x) (range 101 300)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-middle-insert))
                '(64 64 64 64 44))
  (define wide-full-insert (adapter:pvector-insert wide-insert-base 100 'y))
  (check-model wide-full-insert (append (range 100) '(y) (range 100 300)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-full-insert))
                '(64 36 1 28 64 64 44))
  (define-values (single-delete deleted)
    (adapter:pvector-delete single-chunk 5))
  (check-equal? deleted 5)
  (check-model single-delete '(0 1 2 3 4 6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-delete))
                '(9))
  (define-values (single-pop-left-value single-pop-left-rest)
    (adapter:pvector-pop-left single-chunk))
  (check-equal? single-pop-left-value 0)
  (check-model single-pop-left-rest '(1 2 3 4 5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-pop-left-rest))
                '(9))
  (define-values (single-pop-right-value single-pop-right-rest)
    (adapter:pvector-pop-right single-chunk))
  (check-equal? single-pop-right-value 9)
  (check-model single-pop-right-rest '(0 1 2 3 4 5 6 7 8))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector single-pop-right-rest))
                '(9))
  (define small-append
    (adapter:pvector-append (adapter:pvector 1 2 3)
                            (adapter:pvector 4 5 6)))
  (check-model small-append '(1 2 3 4 5 6))
  (check-equal? (vector-length (adapter:pvector->chunk-vector small-append)) 1)
  (define merged-endpoints
    (adapter:pvector-append (adapter:pvector-take pv 3)
                            (adapter:pvector-drop pv 128)))
  (check-model merged-endpoints (append (take xs 3) (drop xs 128)))
  (check-equal? (vector-length (adapter:pvector->chunk-vector merged-endpoints)) 1)
  (define deep-boundary-append
    (adapter:pvector-append (adapter:pvector-take pv 70)
                            (adapter:pvector-drop pv 100)))
  (check-model deep-boundary-append (append (take xs 70) (drop xs 100)))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector deep-boundary-append))
                '(64 6 28 2))
  (define-values (left rest-left) (adapter:pvector-pop-left pv))
  (check-equal? left 0)
  (check-model rest-left (range 1 130))
  (define-values (right rest-right) (adapter:pvector-pop-right pv))
  (check-equal? right 129)
  (check-model rest-right (range 129))
  (for ([pos (in-list '(0 1 63 64 65 100 129 130))])
    (define-values (l r) (adapter:pvector-split-at pv pos))
    (check-model l (take xs pos))
    (check-model r (drop xs pos))
    (check-model (adapter:pvector-take pv pos) (take xs pos))
    (check-model (adapter:pvector-drop pv pos) (drop xs pos)))
  (define-values (front-split-left front-split-right)
    (adapter:pvector-split-at pv 3))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector front-split-left))
                '(3))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector front-split-right))
                '(61 64 2))
  (define-values (back-split-left back-split-right)
    (adapter:pvector-split-at pv 129))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector back-split-left))
                '(64 64 1))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector back-split-right))
                '(1))
  (define cross-chunk-copy (adapter:pvector-copy pv 63 100))
  (check-model cross-chunk-copy (take (drop xs 63) 37))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector cross-chunk-copy))
                '(1 36))
  (define three-chunk-copy (adapter:pvector-copy pv 60 129))
  (check-model three-chunk-copy (take (drop xs 60) 69))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector three-chunk-copy))
                '(4 64 1))
  (define same-chunk-copy (adapter:pvector-copy pv 2 62))
  (check-model same-chunk-copy (take (drop xs 2) 60))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector same-chunk-copy))
                '(60))
  (define wide-xs (range 300))
  (define wide-pv (adapter:list->pvector wide-xs))
  (define wide-middle-copy (adapter:pvector-copy wide-pv 90 230))
  (check-model wide-middle-copy (take (drop wide-xs 90) 140))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-middle-copy))
                '(38 64 38))
  (define wide-inserted (adapter:pvector-insert wide-pv 150 'x))
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-inserted))
                '(64 64 22 1 42 64 44))
  (define-values (wide-deleted wide-value)
    (adapter:pvector-delete wide-inserted 150))
  (check-equal? wide-value 'x)
  (check-model wide-deleted wide-xs)
  (check-equal? (chunk-vector-lengths (adapter:pvector->chunk-vector wide-deleted))
                '(64 64 22 42 64 44))
  (define large-xs (range 10000))
  (define large-pv (adapter:list->pvector large-xs))
  (check-model (adapter:pvector-copy large-pv 1250 8750)
               (take (drop large-xs 1250) 7500))
  (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
    (let* ([pv (adapter:list->pvector (range 8192))]
           [set-pv (adapter:pvector-set pv 4096 'x)]
           [stats (adapter:pvector-shape-stats set-pv)])
      (check-model set-pv
                   (append (range 4096) '(x) (range 4097 8192)))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 128))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [set-pv (adapter:pvector-set pv 4096 'x)]
           [set-pv* (adapter:pvector-set set-pv 4097 'y)]
           [stats (adapter:pvector-shape-stats set-pv*)])
      (check-model set-pv*
                   (append (range 4096) '(x y) (range 4098 8192)))
      (check-equal? (adapter:pvector-ref set-pv* 4096) 'x)
      (check-equal? (adapter:pvector-ref set-pv* 4097) 'y)
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 0))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [consed (adapter:pvector-cons-left pv 'x)]
           [stats (adapter:pvector-shape-stats consed)])
      (check-model consed (cons 'x (range 8192)))
      (check-equal? (adapter:pvector-ref consed 0) 'x)
      (check-equal? (adapter:pvector-ref consed 1) 0)
      (check-equal? (adapter:pvector-ref consed 8192) 8191)
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 128)
      (check-equal? (hash-ref stats 'shifted-cache-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'shifted-cache-source-start #f) 0)
      (check-equal? (hash-ref stats 'shifted-cache-front-length #f) 1))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [consed (adapter:pvector-cons-right pv 'x)]
           [stats (adapter:pvector-shape-stats consed)])
      (check-model consed (append (range 8192) '(x)))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 129))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [consed (adapter:pvector-cons-right pv 'x)]
           [consed* (adapter:pvector-cons-right consed 'y)]
           [stats (adapter:pvector-shape-stats consed*)])
      (check-model consed* (append (range 8192) '(x y)))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 0))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [stats #f])
      (let-values ([(value rest) (adapter:pvector-pop-left pv)])
        (set! stats (adapter:pvector-shape-stats rest))
        (check-equal? value 0)
        (check-model rest (range 1 8192))
        (check-equal? (adapter:pvector-ref rest 0) 1)
        (check-equal? (adapter:pvector-ref rest 8190) 8191)
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 128)
        (check-equal? (hash-ref stats 'shifted-cache-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'shifted-cache-source-start #f) 1)
        (check-equal? (hash-ref stats 'shifted-cache-front-length #f) 0)))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [stats #f])
      (let-values ([(value rest) (adapter:pvector-pop-right pv)])
        (set! stats (adapter:pvector-shape-stats rest))
        (check-equal? value 8191)
        (check-model rest (range 8191))
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 128)))
    (let* ([pv (adapter:list->pvector (range 8192))])
      (let-values ([(value1 rest1) (adapter:pvector-pop-right pv)])
        (let-values ([(value2 rest2) (adapter:pvector-pop-right rest1)])
          (define stats (adapter:pvector-shape-stats rest2))
          (check-equal? value1 8191)
          (check-equal? value2 8190)
          (check-model rest2 (range 8190))
          (check-equal? (hash-ref stats 'chunk-index-vectors 0) 0))))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [stats #f])
      (let-values ([(rest value) (adapter:pvector-delete pv 8191)])
        (set! stats (adapter:pvector-shape-stats rest))
        (check-equal? value 8191)
        (check-model rest (range 8191))
        (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
        (check-equal? (hash-ref stats 'chunk-index-slots 0) 128)))
    (let* ([pv (adapter:list->pvector (range 16384))]
           [copied (adapter:pvector-copy pv 4096 12288)]
           [stats (adapter:pvector-shape-stats copied)])
      (check-model copied (range 4096 12288))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 128))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [copied (adapter:pvector-copy pv 0 6144)]
           [stats (adapter:pvector-shape-stats copied)])
      (check-model copied (range 0 6144))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 96))
    (let* ([pv (adapter:list->pvector (range 8192))]
           [copied (adapter:pvector-copy pv 2048 8192)]
           [stats (adapter:pvector-shape-stats copied)])
      (check-model copied (range 2048 8192))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 1)
      (check-equal? (hash-ref stats 'chunk-index-slots 0) 96))
    (let* ([pv (adapter:list->pvector (range 16384))]
           [copied (adapter:pvector-copy pv 4100 12292)]
           [stats (adapter:pvector-shape-stats copied)])
      (check-model copied (range 4100 12292))
      (check-equal? (hash-ref stats 'chunk-index-vectors 0) 0)))
  (check-equal? (for/list ([x (adapter:in-pvector pv)]) x)
                xs)
  (check-equal? (for/list ([x (adapter:in-pvector-reverse pv)]) x)
                (reverse xs))
  (check-equal? (for/list ([(x i) (adapter:in-pvector/index pv)])
                  (list x i))
                (for/list ([x (in-list xs)]
                           [i (in-naturals)])
                  (list x i)))
  (check-equal? (for/list ([(x i) (adapter:in-pvector-indexed pv)])
                  (list x i))
                (for/list ([x (in-list xs)]
                           [i (in-naturals)])
                  (list x i)))
  (define indexed-seq (adapter:in-pvector/index pv))
  (check-equal? (for/list ([(x i) indexed-seq]) (list x i))
                (for/list ([x (in-list xs)]
                           [i (in-naturals)])
                  (list x i)))
  (define indexed-alias-seq (adapter:in-pvector-indexed pv))
  (check-equal? (for/list ([(x i) indexed-alias-seq]) (list x i))
                (for/list ([x (in-list xs)]
                           [i (in-naturals)])
                  (list x i)))
  (check-equal? (chunk-vector->list (adapter:pvector->chunk-vector pv))
                xs)
  (check-equal? (chunk-vector->list
                 (adapter:pvector->chunk-vector (adapter:pvector-drop pv 3)))
                (drop xs 3))
  (define seq (adapter:in-pvector pv))
  (check-equal? (for/list ([x seq]) x) xs)
  (check-equal? (for/list ([x seq]) x) xs)
  (define rseq (adapter:in-pvector-reverse pv))
  (check-equal? (for/list ([x rseq]) x) (reverse xs))
  (check-equal? (for/list ([x rseq]) x) (reverse xs))
  (define shifted-pv (adapter:pvector-drop pv 3))
  (define shifted-xs (drop xs 3))
  (define shifted-seq (adapter:in-pvector shifted-pv))
  (check-equal? (for/list ([x shifted-seq]) x) shifted-xs)
  (check-equal? (for/list ([x shifted-seq]) x) shifted-xs)
  (define shifted-rseq (adapter:in-pvector-reverse shifted-pv))
  (check-equal? (for/list ([x shifted-rseq]) x) (reverse shifted-xs))
  (define shifted-indexed-seq (adapter:in-pvector/index shifted-pv))
  (check-equal? (for/list ([(x i) shifted-indexed-seq]) (list x i))
                (for/list ([x (in-list shifted-xs)]
                           [i (in-naturals)])
                  (list x i)))
  (check-model (adapter:for/pvector ([x (in-range 5)]) (* x x))
               '(0 1 4 9 16))
  (check-true (eq? (adapter:for/pvector ([x (adapter:in-pvector pv)]) x)
                   pv))
  (check-true (eq? (adapter:for/pvector ([x pv]) x)
                   pv))
  (check-true (eq? (adapter:for/pvector #:length (adapter:pvector-length pv)
                     ([x (adapter:in-pvector pv)])
                     x)
                   pv))
  (check-true (eq? (adapter:for/pvector #:length (adapter:pvector-length pv)
                     ([x pv])
                     x)
                   pv))
  (check-model (adapter:for/pvector ([x (adapter:in-pvector-reverse pv)]) x)
               (reverse xs))
  (check-model (adapter:for/pvector #:length 3
                 ([x (adapter:in-pvector pv)])
                 x)
               '(0 1 2))
  (check-model (adapter:for/pvector #:length 133
                 ([x (adapter:in-pvector pv)])
                 x)
               (append xs '(0 0 0)))
  (check-exn exn:fail:contract?
             (lambda ()
               (adapter:for/pvector #:length 133 ([x pv]) x)))
  (check-model (adapter:for/pvector ([x (adapter:in-pvector pv)]) (* x x))
               (map (lambda (x) (* x x)) xs))
  (check-model (adapter:for/pvector ([x (in-list xs)]) x)
               xs)
  (let ([value (box 'builder-uniform)]
        [count 0])
    (define pv
      (adapter:for/pvector ([x (in-range 130)])
        (set! count (add1 count))
        value))
    (check-equal? count 130)
    (check-model pv (make-list 130 value))
    (check-eq? (vector-ref (adapter:pvector->vector pv) 64) value)
    (check-eq? (list-ref (adapter:pvector->list pv) 129) value)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (define chunks (adapter:pvector->chunk-vector/shared pv))
      (check-true (eq? (vector-ref chunks 0) (vector-ref chunks 1)))))
  (let ([value (box 'builder-mixed)]
        [count 0])
    (define pv
      (adapter:for/pvector ([x (in-range 130)])
        (set! count (add1 count))
        (if (= x 64) 'other value)))
    (check-equal? count 130)
    (check-model pv
                 (append (make-list 64 value)
                         '(other)
                         (make-list 65 value)))
    (check-eq? (vector-ref (adapter:pvector->vector pv) 63) value)
    (check-equal? (vector-ref (adapter:pvector->vector pv) 64) 'other)
    (check-eq? (list-ref (adapter:pvector->list pv) 129) value)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (define chunks (adapter:pvector->chunk-vector/shared pv))
      (check-false (eq? (vector-ref chunks 0) (vector-ref chunks 1)))))
  (let* ([src (list->vector xs)]
         [pv (adapter:for/pvector ([x (in-vector src)]) x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (let* ([src (list->vector xs)]
         [pv (adapter:for/pvector #:length (vector-length src)
               ([x (in-vector src)])
               x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (let* ([src (list->vector xs)]
         [pv (adapter:for/pvector #:length (vector-length src)
               ([x src])
               x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (check-model (adapter:for/pvector #:length 3
                 ([x (in-vector (list->vector xs))])
                 x)
               '(0 1 2))
  (check-model (adapter:for/pvector #:length 133
                 ([x (in-vector (list->vector xs))])
                 x)
               (append xs '(0 0 0)))
  (let ([count 0])
    (define (get-list)
      (set! count (add1 count))
      xs)
    (check-model (adapter:for/pvector ([x (in-list (get-list))]) x)
                 xs)
    (check-equal? count 1))
  (check-model (adapter:for/pvector #:length 5 #:fill 'done
                 ([x (in-range 3)])
                 x)
               '(0 1 2 done done))
  (let ([value (box 'length-builder-uniform)]
        [count 0])
    (define pv
      (adapter:for/pvector #:length 130 ([x (in-range 130)])
        (set! count (add1 count))
        value))
    (check-equal? count 130)
    (check-model pv (make-list 130 value))
    (check-eq? (vector-ref (adapter:pvector->vector pv) 64) value)
    (check-eq? (list-ref (adapter:pvector->list pv) 129) value)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (define chunks (adapter:pvector->chunk-vector/shared pv))
      (check-true (eq? (vector-ref chunks 0) (vector-ref chunks 1)))))
  (let ([n 5])
    (check-model (adapter:for/pvector #:length n
                   ([x (in-range 0 n)])
                   x)
                 '(0 1 2 3 4)))
  (let ([n 5])
    (check-model (adapter:for/pvector #:length n
                   ([x (in-range 0 n 1)])
                   x)
                 '(0 1 2 3 4)))
  (let ([n 5])
    (check-model (adapter:for/pvector #:length n
                   ([x (in-range 0 n)])
                   (* x x))
                 '(0 1 4 9 16)))
  (let ([n 5])
    (check-model (adapter:for/pvector #:length n
                   ([x (in-range 0 n 1)])
                   (* x x))
                 '(0 1 4 9 16)))
  (check-model (adapter:for*/pvector ([x (in-range 2)] [y (in-range 2)])
                 (list x y))
               '((0 0) (0 1) (1 0) (1 1)))
  (check-true (eq? (adapter:for*/pvector ([x (adapter:in-pvector pv)]) x)
                   pv))
  (check-true (eq? (adapter:for*/pvector ([x pv]) x)
                   pv))
  (check-true (eq? (adapter:for*/pvector #:length (adapter:pvector-length pv)
                     ([x (adapter:in-pvector pv)])
                     x)
                   pv))
  (check-true (eq? (adapter:for*/pvector #:length (adapter:pvector-length pv)
                     ([x pv])
                     x)
                   pv))
  (check-model (adapter:for*/pvector ([x (adapter:in-pvector-reverse pv)]) x)
               (reverse xs))
  (check-model (adapter:for*/pvector #:length 3
                 ([x (adapter:in-pvector pv)])
                 x)
               '(0 1 2))
  (check-model (adapter:for*/pvector #:length 133
                 ([x (adapter:in-pvector pv)])
                 x)
               (append xs '(0 0 0)))
  (check-exn exn:fail:contract?
             (lambda ()
               (adapter:for*/pvector #:length 133 ([x pv]) x)))
  (check-model (adapter:for*/pvector ([x (adapter:in-pvector pv)]) (* x x))
               (map (lambda (x) (* x x)) xs))
  (check-model (adapter:for*/pvector ([x (in-list xs)]) x)
               xs)
  (let ([value (box 'builder-uniform)]
        [count 0])
    (define pv
      (adapter:for*/pvector ([x (in-range 13)] [y (in-range 10)])
        (set! count (add1 count))
        value))
    (check-equal? count 130)
    (check-model pv (make-list 130 value))
    (check-eq? (vector-ref (adapter:pvector->vector pv) 64) value)
    (check-eq? (list-ref (adapter:pvector->list pv) 129) value)
    (when (eq? (adapter:pvector-runtime-adapter-backend) 'core)
      (define chunks (adapter:pvector->chunk-vector/shared pv))
      (check-true (eq? (vector-ref chunks 0) (vector-ref chunks 1)))))
  (let* ([src (list->vector xs)]
         [pv (adapter:for*/pvector ([x (in-vector src)]) x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (let* ([src (list->vector xs)]
         [pv (adapter:for*/pvector #:length (vector-length src)
               ([x (in-vector src)])
               x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (let* ([src (list->vector xs)]
         [pv (adapter:for*/pvector #:length (vector-length src)
               ([x src])
               x)])
    (vector-set! src 0 'changed)
    (check-model pv xs))
  (check-model (adapter:for*/pvector #:length 3
                 ([x (in-vector (list->vector xs))])
                 x)
               '(0 1 2))
  (check-model (adapter:for*/pvector #:length 133
                 ([x (in-vector (list->vector xs))])
                 x)
               (append xs '(0 0 0)))
  (let ([n 5])
    (check-model (adapter:for*/pvector #:length n
                   ([x (in-range 0 n)])
                   x)
                 '(0 1 2 3 4)))
  (let ([n 5])
    (check-model (adapter:for*/pvector #:length n
                   ([x (in-range 0 n 1)])
                   x)
                 '(0 1 2 3 4)))
  (let ([n 5])
    (check-model (adapter:for*/pvector #:length n
                   ([x (in-range 0 n)])
                   (* x x))
                 '(0 1 4 9 16)))
  (let ([n 5])
    (check-model (adapter:for*/pvector #:length n
                   ([x (in-range 0 n 1)])
                   (* x x))
                 '(0 1 4 9 16)))
  (check-model (adapter:for*/pvector #:length 4
                 ([x (in-range 2)] [y (in-range 2)])
                 (list x y))
               '((0 0) (0 1) (1 0) (1 1))))
