#lang racket/base

(require racket/list
         racket/match
         (prefix-in chunked: racket/private/pvector-chunked)
         rackunit)

(define (check-model pv xs)
  (check-true (chunked:pvector? pv))
  (check-equal? (chunked:pvector-length pv) (length xs))
  (check-equal? (chunked:pvector->list pv) xs)
  (check-equal? (vector->list (chunked:pvector->vector pv)) xs)
  (for ([x (in-list xs)]
        [i (in-naturals)])
    (check-equal? (chunked:pvector-ref pv i) x)))

(define (list-set xs i v)
  (append (take xs i) (list v) (drop xs (add1 i))))

(define (list-insert xs i v)
  (append (take xs i) (list v) (drop xs i)))

(define (list-delete xs i)
  (values (append (take xs i) (drop xs (add1 i)))
          (list-ref xs i)))

(define (chunk-vector->list chunks)
  (append*
   (for/list ([chunk (in-vector chunks)])
     (vector->list chunk))))

(define (chunk-vector-lengths chunks)
  (for/list ([chunk (in-vector chunks)])
    (vector-length chunk)))

(test-case "construction and conversion"
  (check-model (chunked:pvector-empty) '())
  (check-true (chunked:pvector-empty? (chunked:pvector-empty)))
  (check-false (chunked:pvector-empty? '(not a pvector)))
  (check-true (eq? (chunked:pvector-empty) (chunked:list->pvector null)))
  (check-true (eq? (chunked:pvector-empty) (chunked:vector->pvector #())))
  (define singleton (chunked:pvector 'one))
  (define-values (singleton-left-value singleton-left-rest)
    (chunked:pvector-pop-left singleton))
  (check-equal? singleton-left-value 'one)
  (check-true (eq? (chunked:pvector-empty) singleton-left-rest))
  (define-values (singleton-right-value singleton-right-rest)
    (chunked:pvector-pop-right singleton))
  (check-equal? singleton-right-value 'one)
  (check-true (eq? (chunked:pvector-empty) singleton-right-rest))
  (define-values (singleton-delete-rest singleton-delete-value)
    (chunked:pvector-delete singleton 0))
  (check-equal? singleton-delete-value 'one)
  (check-true (eq? (chunked:pvector-empty) singleton-delete-rest))
  (check-model (chunked:pvector 1 2 3) '(1 2 3))
  (define small-conversion (chunked:pvector 1 2 3 4 5))
  (define small-conversion-vector (chunked:pvector->vector small-conversion))
  (vector-set! small-conversion-vector 0 'changed)
  (check-equal? (vector->list small-conversion-vector) '(changed 2 3 4 5))
  (check-model small-conversion '(1 2 3 4 5))
  (check-model (chunked:make-pvector 5 'x) '(x x x x x))
  (check-model (chunked:list->pvector (range 130)) (range 130))
  (check-model (chunked:vector->pvector (list->vector (range 130))) (range 130))
  (define cached-conversion (chunked:list->pvector (range 130)))
  (define exposed-chunks (chunked:pvector->chunk-vector cached-conversion))
  (vector-set! exposed-chunks 0 '#(bad))
  (check-equal? (chunked:pvector-ref cached-conversion 64) 64)
  (check-equal? (chunk-vector->list (chunked:pvector->chunk-vector cached-conversion))
                (range 130))
  (define exposed-vector (chunked:pvector->vector cached-conversion))
  (vector-set! exposed-vector 64 'changed)
  (check-equal? (chunked:pvector-ref cached-conversion 64) 64)
  (check-model (chunked:sequence->pvector (in-range 130)) (range 130))
  (check-model (chunked:sequence->pvector (in-range 0 130 1)) (range 130))
  (check-model (chunked:sequence->pvector (in-range 1 5)) '(1 2 3 4))
  (check-model (chunked:sequence->pvector (in-range 0 8 2)) '(0 2 4 6))
  (check-model (chunked:sequence->pvector (in-range 8 0 -2)) '(8 6 4 2))
  (check-model (chunked:sequence->pvector 130) (range 130))
  (check-true (eq? (chunked:pvector-empty)
                   (chunked:sequence->pvector 0))))

(test-case "ref set and endpoints"
  (define pv (chunked:list->pvector (range 130)))
  (check-equal? (chunked:pvector-view-left pv) 0)
  (check-equal? (chunked:pvector-view-right pv) 129)
  (check-equal? (chunked:pvector-ref pv 64) 64)
  (check-true (eq? pv (chunked:pvector-set pv 64 64)))
  (check-false (eq? pv (chunked:pvector-set pv 64 'x)))
  (check-model (chunked:pvector-set pv 64 'x)
               (list-set (range 130) 64 'x))
  (define-values (middle-delete middle-deleted)
    (chunked:pvector-delete pv 32))
  (check-equal? middle-deleted 32)
  (check-model middle-delete (let-values ([(xs _) (list-delete (range 130) 32)]) xs))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector middle-delete))
                '(63 64 2))
  (define-values (last-chunk-delete last-chunk-deleted)
    (chunked:pvector-delete pv 128))
  (check-equal? last-chunk-deleted 128)
  (check-model last-chunk-delete (let-values ([(xs _) (list-delete (range 130) 128)]) xs))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector last-chunk-delete))
                '(64 64 1))
  (check-model (chunked:pvector-cons-left pv 'left)
               (cons 'left (range 130)))
  (check-model (chunked:pvector-cons-right pv 'right)
               (append (range 130) '(right)))
  (define packed-right
    (for/fold ([pv (chunked:pvector-empty)]) ([i (in-range 9)])
      (chunked:pvector-cons-right pv i)))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector packed-right))
                '(8 1))
  (define packed-left
    (for/fold ([pv (chunked:pvector-empty)]) ([i (in-range 9)])
      (chunked:pvector-cons-left pv i)))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector packed-left))
                '(1 8))
  (define single-chunk (chunked:pvector 0 1 2 3 4 5 6 7 8 9))
  (check-true (eq? single-chunk (chunked:pvector-set single-chunk 5 5)))
  (define single-set (chunked:pvector-set single-chunk 5 'x))
  (check-model single-set '(0 1 2 3 4 x 6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-set))
                '(10))
  (define-values (single-left single-right)
    (chunked:pvector-split-at single-chunk 5))
  (check-model single-left '(0 1 2 3 4))
  (check-model single-right '(5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-left))
                '(5))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-right))
                '(5))
  (define-values (split-left split-value split-right)
    (chunked:pvector-split single-chunk 5))
  (check-model split-left '(0 1 2 3 4))
  (check-equal? split-value 5)
  (check-model split-right '(6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector split-right))
                '(4))
  (define-values (front-value-left front-value front-value-right)
    (chunked:pvector-split pv 3))
  (check-equal? front-value 3)
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector front-value-left))
                '(3))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector front-value-right))
                '(60 64 2))
  (define-values (back-value-left back-value back-value-right)
    (chunked:pvector-split pv 129))
  (check-equal? back-value 129)
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector back-value-left))
                '(64 64 1))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector back-value-right))
                '())
  (define single-insert (chunked:pvector-insert single-chunk 5 'x))
  (check-model single-insert '(0 1 2 3 4 x 5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-insert))
                '(11))
  (define-values (single-delete deleted)
    (chunked:pvector-delete single-chunk 5))
  (check-equal? deleted 5)
  (check-model single-delete '(0 1 2 3 4 6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-delete))
                '(9))
  (define-values (single-pop-left-value single-pop-left-rest)
    (chunked:pvector-pop-left single-chunk))
  (check-equal? single-pop-left-value 0)
  (check-model single-pop-left-rest '(1 2 3 4 5 6 7 8 9))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-pop-left-rest))
                '(9))
  (define-values (single-pop-right-value single-pop-right-rest)
    (chunked:pvector-pop-right single-chunk))
  (check-equal? single-pop-right-value 9)
  (check-model single-pop-right-rest '(0 1 2 3 4 5 6 7 8))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector single-pop-right-rest))
                '(9))
  (define-values (left rest-left) (chunked:pvector-pop-left pv))
  (check-equal? left 0)
  (check-model rest-left (range 1 130))
  (define-values (right rest-right) (chunked:pvector-pop-right pv))
  (check-equal? right 129)
  (check-model rest-right (range 129)))

(test-case "append split take drop and copy"
  (define xs (range 130))
  (define pv (chunked:list->pvector xs))
  (check-model (chunked:pvector-append (chunked:list->pvector (take xs 65))
                                       (chunked:list->pvector (drop xs 65)))
               xs)
  (define small-append
    (chunked:pvector-append (chunked:pvector 1 2 3)
                            (chunked:pvector 4 5 6)))
  (check-model small-append '(1 2 3 4 5 6))
  (check-equal? (vector-length (chunked:pvector->chunk-vector small-append)) 1)
  (define merged-endpoints
    (chunked:pvector-append (chunked:pvector-take pv 3)
                            (chunked:pvector-drop pv 128)))
  (check-model merged-endpoints (append (take xs 3) (drop xs 128)))
  (check-equal? (vector-length (chunked:pvector->chunk-vector merged-endpoints)) 1)
  (define deep-boundary-append
    (chunked:pvector-append (chunked:pvector-take pv 70)
                            (chunked:pvector-drop pv 100)))
  (check-model deep-boundary-append (append (take xs 70) (drop xs 100)))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector deep-boundary-append))
                '(64 6 28 2))
  (for ([pos (in-list '(0 1 63 64 65 100 129 130))])
    (define-values (left right) (chunked:pvector-split-at pv pos))
    (check-model left (take xs pos))
    (check-model right (drop xs pos))
    (check-model (chunked:pvector-take pv pos) (take xs pos))
    (check-model (chunked:pvector-drop pv pos) (drop xs pos))
    (check-model (chunked:pvector-take-right pv pos) (take-right xs pos))
    (check-model (chunked:pvector-drop-right pv pos) (drop-right xs pos)))
  (define-values (empty-left whole-right) (chunked:pvector-split-at pv 0))
  (define-values (whole-left empty-right) (chunked:pvector-split-at pv 130))
  (check-true (eq? (chunked:pvector-empty) empty-left))
  (check-true (eq? (chunked:pvector-empty) empty-right))
  (check-true (eq? (chunked:pvector-empty) (chunked:pvector-take-right pv 0)))
  (check-true (eq? (chunked:pvector-empty) (chunked:pvector-drop-right pv 130)))
  (check-true (eq? pv whole-right))
  (check-true (eq? pv whole-left))
  (check-true (eq? pv (chunked:pvector-take-right pv 130)))
  (check-true (eq? pv (chunked:pvector-drop-right pv 0)))
  (define-values (front-split-left front-split-right)
    (chunked:pvector-split-at pv 3))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector front-split-left))
                '(3))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector front-split-right))
                '(61 64 2))
  (define-values (back-split-left back-split-right)
    (chunked:pvector-split-at pv 129))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector back-split-left))
                '(64 64 1))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector back-split-right))
                '(1))
  (define take-right-end (chunked:pvector-take-right pv 3))
  (check-model take-right-end (take-right xs 3))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector take-right-end))
                '(1 2))
  (define drop-right-end (chunked:pvector-drop-right pv 2))
  (check-model drop-right-end (drop-right xs 2))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector drop-right-end))
                '(64 64))
  (define-values (left value right) (chunked:pvector-split pv 64))
  (check-model left (take xs 64))
  (check-equal? value 64)
  (check-model right (drop xs 65))
  (for* ([start (in-list '(0 1 63 64 65 100 130))]
         [end (in-list '(0 1 63 64 65 100 130))]
         #:when (<= start end))
    (check-model (chunked:pvector-copy pv start end)
                 (take (drop xs start) (- end start))))
  (define cross-chunk-copy (chunked:pvector-copy pv 63 100))
  (check-model cross-chunk-copy (take (drop xs 63) 37))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector cross-chunk-copy))
                '(1 36))
  (define three-chunk-copy (chunked:pvector-copy pv 60 129))
  (check-model three-chunk-copy (take (drop xs 60) 69))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector three-chunk-copy))
                '(4 64 1))
  (define same-chunk-copy (chunked:pvector-copy pv 2 62))
  (check-model same-chunk-copy (take (drop xs 2) 60))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector same-chunk-copy))
                '(60))
  (define wide-xs (range 300))
  (define wide-pv (chunked:list->pvector wide-xs))
  (define wide-middle-copy (chunked:pvector-copy wide-pv 90 230))
  (check-model wide-middle-copy (take (drop wide-xs 90) 140))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector wide-middle-copy))
                '(38 64 38)))

(test-case "insert delete and sequence"
  (define pv0 (chunked:list->pvector (range 70)))
  (check-model (chunked:pvector-insert pv0 0 'a)
               (list-insert (range 70) 0 'a))
  (define tail-insert (chunked:pvector-insert pv0 64 'b))
  (check-model tail-insert (list-insert (range 70) 64 'b))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector tail-insert))
                '(64 7))
  (define wide-insert-base (chunked:list->pvector (range 300)))
  (define-values (wide-middle-open wide-middle-deleted)
    (chunked:pvector-delete wide-insert-base 100))
  (check-equal? wide-middle-deleted 100)
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector wide-middle-open))
                '(64 63 64 64 44))
  (define wide-middle-insert (chunked:pvector-insert wide-middle-open 100 'x))
  (check-model wide-middle-insert (append (range 100) '(x) (range 101 300)))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector wide-middle-insert))
                '(64 64 64 64 44))
  (define wide-full-insert (chunked:pvector-insert wide-insert-base 100 'y))
  (check-model wide-full-insert (append (range 100) '(y) (range 100 300)))
  (check-equal? (chunk-vector-lengths (chunked:pvector->chunk-vector wide-full-insert))
                '(64 36 1 28 64 64 44))
  (check-model (chunked:pvector-insert pv0 70 'c)
               (list-insert (range 70) 70 'c))
  (define-values (pv1 deleted) (chunked:pvector-delete pv0 64))
  (check-equal? deleted 64)
  (check-model pv1 (let-values ([(xs _) (list-delete (range 70) 64)]) xs))
  (check-equal? (for/list ([x (chunked:in-pvector pv0)]) x)
                (range 70))
  (check-equal? (for/list ([x (chunked:in-pvector-reverse pv0)]) x)
                (reverse (range 70)))
  (check-equal? (for/list ([(x i) (chunked:in-pvector/index pv0)])
                  (list x i))
                (for/list ([x (in-range 70)]
                           [i (in-naturals)])
                  (list x i)))
  (check-equal? (for/list ([(x i) (chunked:in-pvector-indexed pv0)])
                  (list x i))
                (for/list ([x (in-range 70)]
                           [i (in-naturals)])
                  (list x i)))
  (define indexed-seq (chunked:in-pvector/index pv0))
  (check-equal? (for/list ([(x i) indexed-seq]) (list x i))
                (for/list ([x (in-range 70)]
                           [i (in-naturals)])
                  (list x i)))
  (define indexed-alias-seq (chunked:in-pvector-indexed pv0))
  (check-equal? (for/list ([(x i) indexed-alias-seq]) (list x i))
                (for/list ([x (in-range 70)]
                           [i (in-naturals)])
                  (list x i)))
  (check-equal? (chunk-vector->list (chunked:pvector->chunk-vector pv0))
                (range 70))
  (check-equal? (chunk-vector->list
                 (chunked:pvector->chunk-vector (chunked:pvector-drop pv0 3)))
                (range 3 70))
  (define seq (chunked:in-pvector pv0))
  (check-equal? (for/list ([x seq]) x) (range 70))
  (check-equal? (for/list ([x seq]) x) (range 70))
  (define rseq (chunked:in-pvector-reverse pv0))
  (check-equal? (for/list ([x rseq]) x) (reverse (range 70)))
  (check-equal? (for/list ([x rseq]) x) (reverse (range 70)))
  (define wide-pv (chunked:sequence->pvector (in-range 130)))
  (define shifted-pv (chunked:pvector-drop wide-pv 3))
  (define shifted-xs (range 3 130))
  (define shifted-seq (chunked:in-pvector shifted-pv))
  (check-equal? (for/list ([x shifted-seq]) x) shifted-xs)
  (check-equal? (for/list ([x shifted-seq]) x) shifted-xs)
  (define shifted-rseq (chunked:in-pvector-reverse shifted-pv))
  (check-equal? (for/list ([x shifted-rseq]) x) (reverse shifted-xs))
  (define shifted-indexed-seq (chunked:in-pvector/index shifted-pv))
  (check-equal? (for/list ([(x i) shifted-indexed-seq]) (list x i))
                (for/list ([x (in-list shifted-xs)]
                           [i (in-naturals)])
                  (list x i)))
  (check-model (chunked:for/pvector ([x (in-range 5)]) (* x x))
               '(0 1 4 9 16))
  (check-model (chunked:for*/pvector ([x (in-range 2)] [y (in-range 2)])
                 (list x y))
               '((0 0) (0 1) (1 0) (1 1))))

(test-case "seeded randomized list model"
  (random-seed 20260611)
  (let loop ([step 0] [pv (chunked:pvector-empty)] [xs '()])
    (check-model pv xs)
    (when (< step 250)
      (define len (length xs))
      (define op (if (zero? len) (random 2) (random 7)))
      (define-values (pv* xs*)
        (case op
          [(0)
           (define value (list 'r step))
           (values (chunked:pvector-cons-right pv value)
                   (append xs (list value)))]
          [(1)
           (define value (list 'l step))
           (values (chunked:pvector-cons-left pv value)
                   (cons value xs))]
          [(2)
           (define i (random len))
           (define value (list 's step))
           (values (chunked:pvector-set pv i value)
                   (list-set xs i value))]
          [(3)
           (define i (random (add1 len)))
           (define value (list 'i step))
           (values (chunked:pvector-insert pv i value)
                   (list-insert xs i value))]
          [(4)
           (define i (random len))
           (define-values (pv-rest pv-deleted) (chunked:pvector-delete pv i))
           (define-values (xs-rest xs-deleted) (list-delete xs i))
           (check-equal? pv-deleted xs-deleted)
           (values pv-rest xs-rest)]
          [(5)
           (define i (random (add1 len)))
           (values (chunked:pvector-take pv i) (take xs i))]
          [else
           (define i (random (add1 len)))
           (values (chunked:pvector-drop pv i) (drop xs i))]))
      (loop (add1 step) pv* xs*))))
