#ifndef __RKTRANDOM_H__
#define __RKTRANDOM_H__ 1

/*

The rktrandom library is Racket's built-in high-performance
non-cryptographic random-number subsystem. It is a static library
parallel to rktcrypto, linked into the Racket executable, with
bindings generated by "../rktio/parse.rkt" (which recognizes the
RKTRANDOM_ macro vocabulary).

These generators are for simulation, sampling, randomized algorithms,
and testing. They are deterministic given a seed and are NOT
cryptographically secure; for secrets, use rktcrypto
(`crypto-random-bytes`).

Conventions:

 - A generator's state lives in a caller-provided buffer of
   RKTRANDOM_STATE_SIZE bytes (a Racket byte string). All state words
   are stored as native-endian uint64_t at 8-byte offsets, so the
   buffer must be 8-byte aligned (Racket byte strings are). Layouts
   are documented per generator below and are stable, so states can
   be serialized and restored across runs and platforms of the same
   endianness.

 - Buffer arguments follow the rktio convention: pointer plus `start`
   and `end` byte offsets.

 - Output is defined as the generator's uint64 sequence serialized
   little-endian; a fill whose length is not a multiple of 8 takes
   the low-order prefix of a final uint64 and discards the rest, so
   fill lengths do not affect the underlying sequence position by
   more than one draw.

 - All functions are thread-safe with respect to distinct states; no
   function has global state.

 - A return type `int` used as a boolean is 1 for success/true and 0
   for failure/false.

*/

#include <stdint.h>
#include <stddef.h>

#ifndef RKTRANDOM_EXTERN
# define RKTRANDOM_EXTERN extern
#endif

#define RKTRANDOM_EXTERN_NOERR RKTRANDOM_EXTERN

/*************************************************/
/* Generators                                    */

/* Generator ids. These become Racket-side constants via parse.rkt.

   State layouts (uint64 words at 8-byte offsets from the state
   pointer):

   XOSHIRO256PP / XOSHIRO256SS: s0 s1 s2 s3   (never all zero)
   XOROSHIRO128PP:              s0 s1         (never both zero)
   SFC64:                       a b c counter
   PCG64DXSM:                   state_hi state_lo inc_hi inc_lo
                                (inc must be odd, i.e. inc_lo bit 0 set)
   PHILOX4X64:                  ctr0 ctr1 ctr2 ctr3 key0 key1
                                buf0 buf1 buf2 buf3 buf_pos          */
#define RKTRANDOM_XOSHIRO256PP   1
#define RKTRANDOM_XOSHIRO256SS   2
#define RKTRANDOM_XOROSHIRO128PP 3
#define RKTRANDOM_SFC64          4
#define RKTRANDOM_PCG64DXSM      5
#define RKTRANDOM_PHILOX4X64     6

#define RKTRANDOM_GEN_FIRST 1
#define RKTRANDOM_GEN_LAST  6

/* Enough for any generator's state; fixed for ABI stability. */
#define RKTRANDOM_STATE_SIZE 128

RKTRANDOM_EXTERN_NOERR int rktrandom_state_size(int gen);
/* Returns the number of state bytes actually used by `gen` (at most
   RKTRANDOM_STATE_SIZE), or 0 if `gen` is not a valid generator
   id. */

RKTRANDOM_EXTERN_NOERR int rktrandom_init(int gen, unsigned char *state,
                                          const unsigned char *seed, intptr_t seed_start,
                                          intptr_t seq);
/* Initializes `state` for `gen` from the 32 bytes
   `seed[seed_start..seed_start+32)` and a stream selector `seq`
   (treated as unsigned). Distinct `seq` values give decorrelated
   start points (derived via a splitmix64 chain); for guaranteed
   non-overlap use rktrandom_jump/rktrandom_long_jump, or
   PHILOX4X64/PCG64DXSM whose `seq` selects mathematically distinct
   streams. Always returns 1 for a valid `gen`, 0 otherwise. */

RKTRANDOM_EXTERN_NOERR int rktrandom_init_int(int gen, unsigned char *state,
                                              intptr_t seed, intptr_t seq);
/* Like rktrandom_init, but expands a single machine-integer seed
   (treated as unsigned) via splitmix64, per the xoshiro authors'
   recommendation. */

RKTRANDOM_EXTERN_NOERR int rktrandom_fill(int gen, unsigned char *state,
                                          unsigned char *buf, intptr_t start, intptr_t end);
/* Fills `buf[start..end)` with the generator's output stream
   (little-endian uint64s, final word truncated as described above).
   This is the bulk path: state stays in registers for the whole
   fill. Returns 1, or 0 on a bad `gen`. */

/*************************************************/
/* Parallel substreams                           */

RKTRANDOM_EXTERN_NOERR int rktrandom_jump(int gen, unsigned char *state);
/* Advances `state` by the generator's jump polynomial:
   XOSHIRO256*: 2^128 steps; XOROSHIRO128PP: 2^64 steps;
   PCG64DXSM: 2^64 steps; PHILOX4X64: 2^64 counter blocks.
   Returns 1, or 0 if `gen` has no jump (SFC64). */

RKTRANDOM_EXTERN_NOERR int rktrandom_long_jump(int gen, unsigned char *state);
/* Like rktrandom_jump but further: XOSHIRO256*: 2^192 steps;
   XOROSHIRO128PP: 2^96 steps. Returns 0 for generators without a
   long jump (SFC64, PCG64DXSM, PHILOX4X64). */

/*************************************************/
/* Fused distribution fills                      */

/* These consume the generator's uint64 stream and write arrays of
   native-endian doubles (or uint64s), so a whole vector of variates
   costs one call. `end - start` must be a multiple of 8; otherwise
   the call returns 0 and writes nothing.

   rktrandom_fill_f64 consumes exactly one uint64 per double and is
   deterministic across platforms. The normal/exponential fills use
   ziggurat rejection: they consume generator words in chunks and
   discard the chunk remainder at the end of each call, and their
   slow path goes through libm, so their streams are deterministic
   for a given platform and call sequence rather than bit-portable. */

RKTRANDOM_EXTERN_NOERR int rktrandom_fill_f64(int gen, unsigned char *state,
                                              unsigned char *buf, intptr_t start, intptr_t end);
/* Uniform [0,1) doubles with 53 random bits each. */

RKTRANDOM_EXTERN_NOERR int rktrandom_fill_normal(int gen, unsigned char *state,
                                                 unsigned char *buf, intptr_t start, intptr_t end);
/* Standard normal N(0,1) doubles (256-layer ziggurat). */

RKTRANDOM_EXTERN_NOERR int rktrandom_fill_exp(int gen, unsigned char *state,
                                              unsigned char *buf, intptr_t start, intptr_t end);
/* Standard exponential Exp(1) doubles (256-layer ziggurat). */

RKTRANDOM_EXTERN_NOERR int rktrandom_fill_bounded(int gen, unsigned char *state,
                                                  unsigned char *buf, intptr_t start, intptr_t end,
                                                  intptr_t bound);
/* Unbiased uniform uint64s in [0,bound), written little-endian, via
   Lemire multiply-shift rejection; `bound` must be positive.
   Deterministic across platforms. */

/*************************************************/
/* Self-test                                     */

RKTRANDOM_EXTERN_NOERR int rktrandom_selftest(void);
/* Runs the known-answer self-tests for every generator (vectors
   cross-checked against the reference implementations: Vigna's
   xoshiro/xoroshiro C, NumPy's sfc64/pcg64-dxsm/philox). Returns 1
   if all pass. */

#endif /* __RKTRANDOM_H__ */
