/* Extracted from rktio.h by rktio/parse.rkt */
Sforeign_symbol("rktrandom_state_size", (void *)rktrandom_state_size);
Sforeign_symbol("rktrandom_init", (void *)rktrandom_init);
Sforeign_symbol("rktrandom_init_int", (void *)rktrandom_init_int);
Sforeign_symbol("rktrandom_fill", (void *)rktrandom_fill);
Sforeign_symbol("rktrandom_jump", (void *)rktrandom_jump);
Sforeign_symbol("rktrandom_long_jump", (void *)rktrandom_long_jump);
Sforeign_symbol("rktrandom_fill_f64", (void *)rktrandom_fill_f64);
Sforeign_symbol("rktrandom_fill_normal", (void *)rktrandom_fill_normal);
Sforeign_symbol("rktrandom_fill_exp", (void *)rktrandom_fill_exp);
Sforeign_symbol("rktrandom_fill_bounded", (void *)rktrandom_fill_bounded);
Sforeign_symbol("rktrandom_selftest", (void *)rktrandom_selftest);
