#!/usr/bin/env python3
# Streaming CIOS Montgomery multiply, width K, register-resident accumulator.
# The CIOS one-word down-shift after each reduction is implemented by ROTATING
# the accumulator's base register each (fully unrolled) iteration -- so logical
# acc[j] maps to physical acc[(base+j) mod (K+2)] and no shift moves are emitted.
# Operands a[]/m[] are streamed from memory with a serial single-word MAC (one
# lo/hi/carry temp), keeping register pressure at ~K+2 (acc) + a few. Fits k=16.
# ABI: x0=r, x1=a, x2=b, x3=m, x4=n0.
import sys
K=int(sys.argv[1]); out=sys.argv[2]; M=K+2
L=[]; e=lambda s="":L.append(s)
def A(base,j): return f"x.acc{(base+j)%M}"     # physical reg for logical acc[j]

def mac_row(base, src_ptr, factor):            # logical acc[0..K-1] += src[j]*factor
    e("  mov x.carry, xzr")
    for j in range(K):
        e(f"  ldr x.tmp, [{src_ptr}, #{j*8}]")
        e(f"  mul x.lo, x.tmp, {factor}")
        e(f"  umulh x.hi, x.tmp, {factor}")
        e(f"  adds {A(base,j)}, {A(base,j)}, x.lo")
        e("  adc x.hi, x.hi, xzr")
        e(f"  adds {A(base,j)}, {A(base,j)}, x.carry")
        e("  adc x.carry, x.hi, xzr")
    e(f"  adds {A(base,K)}, {A(base,K)}, x.carry")
    e(f"  adc {A(base,K+1)}, {A(base,K+1)}, xzr")

def reduce(base):                              # returns new base (shift by 1)
    e(f"  mul x.mm, {A(base,0)}, x.n0")
    e("  mov x.carry, xzr")
    for j in range(K):
        e(f"  ldr x.tmp, [x.m, #{j*8}]")
        e(f"  mul x.lo, x.tmp, x.mm")
        e(f"  umulh x.hi, x.tmp, x.mm")
        e(f"  adds {A(base,j)}, {A(base,j)}, x.lo")
        e("  adc x.hi, x.hi, xzr")
        e(f"  adds {A(base,j)}, {A(base,j)}, x.carry")
        e("  adc x.carry, x.hi, xzr")
    e(f"  adds {A(base,K)}, {A(base,K)}, x.carry")
    e(f"  adc {A(base,K+1)}, {A(base,K+1)}, xzr")
    # logical acc[0] is now 0 (dropped by base++); the freed top slot must be 0
    e(f"  mov {A(base,0)}, xzr")                # this physical reg becomes new acc[K+1]
    return (base+1)%M

e(f"// GENERATED by gen_montmul_stream.py K={K} (rotating base) -- do not edit.")
e(f".function bn_mul_mont_k{K} export (")
e("  in: x.r, x.a, x.b, x.m, x.n0")
e(")")
e("entry:")
e("  .save all")
for j in range(M): e(f"  mov x.acc{j}, xzr")
base=0
for i in range(K):
    e(f"  // b[{i}]  (base={base})")
    e(f"  ldr x.bi, [x.b, #{i*8}]")
    mac_row(base, "x.a", "x.bi")
    base=reduce(base)
# conditional subtract m ; result is logical acc[0..K-1], overflow acc[K]
for j in range(K):
    e(f"  ldr x.tmp, [x.m, #{j*8}]")
    if j==0: e(f"  subs x.s{j}, {A(base,j)}, x.tmp")
    else:    e(f"  sbcs x.s{j}, {A(base,j)}, x.tmp")
e(f"  sbcs xzr, {A(base,K)}, xzr")
for j in range(K): e(f"  csel x.o{j}, x.s{j}, {A(base,j)}, cs")
for j in range(K): e(f"  str x.o{j}, [x.r, #{j*8}]")
e("  .restore all")
e("  ret")
e(".end")
open(out,"w").write("\n".join(L)+"\n")
print("wrote",out,f"K={K} ({len(L)} lines)")
