#!/usr/bin/env python3
# Fused Keccak absorb kernels (one per SHA3/SHAKE rate): the 1600-bit state stays
# resident in vector registers across ALL blocks, each block's rate words XORed
# directly into the register state and permuted in place -- no per-block
# ctx->state load/store round-trip (the ~1% that kept SHA3 just under OpenSSL).
# Emitted for every rate the sponge uses. Mov-free rho/pi matches OpenSSL's ce.
# ABI per kernel: keccak_absorb<W>_asm(uint64_t st[25], const uint8_t*data,
#                                      long nblk, const uint64_t rc[24])
import sys
RATES = [21, 18, 17, 13, 9]   # SHAKE128, SHA3-224, SHA3-256/SHAKE256, SHA3-384, SHA3-512
CYCLE = [(10,1,63),(7,0,61),(11,2,58),(17,1,54),(18,2,49),(3,3,43),(5,3,36),(16,0,28),
 (8,1,19),(21,3,9),(24,1,62),(4,4,50),(15,4,37),(23,0,23),(19,3,8),(13,4,56),
 (12,3,39),(2,2,21),(20,2,2),(14,0,46),(22,4,25),(9,2,3),(6,4,44),(1,1,20)]
def ln(i): return "v.ln%d" % i
D = {0:"v.t5", 1:"v.t6", 2:"v.t1", 3:"v.t2", 4:"v.t3"}
def kernel(W):
    L = [".function keccak_absorb%d_asm export (" % W, "  in: x.st, x.data, x.nblk, x.rc", ")",
         "entry:", "  .save all"]
    for i in range(25): L.append("  ld1r { %s.2d }, [x.st], #8" % ln(i))
    L.append("  sub x.st, x.st, #200")
    L.append("block:")
    for w in range(W):
        L.append("  ld1r { v.t0.2d }, [x.data], #8")
        L.append("  eor %s.16b, %s.16b, v.t0.16b" % (ln(w), ln(w)))
    L.append("  mov x.i, xzr")
    L.append("round:")
    for c in range(5):
        L.append("  eor3 v.t%d.16b, %s.16b, %s.16b, %s.16b" % (c, ln(c), ln(c+5), ln(c+10)))
        L.append("  eor3 v.t%d.16b, v.t%d.16b, %s.16b, %s.16b" % (c, c, ln(c+15), ln(c+20)))
    L.append("  rax1 v.t5.2d, v.t4.2d, v.t1.2d")
    L.append("  rax1 v.t6.2d, v.t0.2d, v.t2.2d")
    L.append("  rax1 v.t1.2d, v.t1.2d, v.t3.2d")
    L.append("  rax1 v.t2.2d, v.t2.2d, v.t4.2d")
    L.append("  rax1 v.t3.2d, v.t3.2d, v.t0.2d")
    L.append("  eor %s.16b, %s.16b, v.t5.16b" % (ln(0), ln(0)))
    L.append("  mov v.t0.16b, %s.16b" % ln(1))
    for i in range(len(CYCLE)-1, 0, -1):
        dst, dcol, rot = CYCLE[i]; src = CYCLE[i-1][0]
        L.append("  xar %s.2d, %s.2d, %s.2d, #%d" % (ln(dst), ln(src), D[dcol], rot))
    dst0, dcol0, rot0 = CYCLE[0]
    L.append("  xar %s.2d, v.t0.2d, %s.2d, #%d" % (ln(dst0), D[dcol0], rot0))
    for base in (0,5,10,15,20):
        b0,b1,b2,b3,b4 = base,base+1,base+2,base+3,base+4
        L.append("  mov v.t5.16b, %s.16b" % ln(b0))
        L.append("  mov v.t6.16b, %s.16b" % ln(b1))
        L.append("  bcax %s.16b, v.t5.16b, %s.16b, v.t6.16b" % (ln(b0), ln(b2)))
        L.append("  bcax %s.16b, v.t6.16b, %s.16b, %s.16b" % (ln(b1), ln(b3), ln(b2)))
        L.append("  bcax %s.16b, %s.16b, %s.16b, %s.16b" % (ln(b2), ln(b2), ln(b4), ln(b3)))
        L.append("  bcax %s.16b, %s.16b, v.t5.16b, %s.16b" % (ln(b3), ln(b3), ln(b4)))
        L.append("  bcax %s.16b, %s.16b, v.t6.16b, v.t5.16b" % (ln(b4), ln(b4)))
    L.append("  add x.rcp, x.rc, x.i")
    L.append("  ld1r { v.t0.2d }, [x.rcp]")
    L.append("  eor %s.16b, %s.16b, v.t0.16b" % (ln(0), ln(0)))
    L.append("  add x.i, x.i, #8")
    L.append("  cmp x.i, #192")
    L.append("  b.lt round")
    L.append("  subs x.nblk, x.nblk, #1")
    L.append("  b.ne block")
    for i in range(25): L.append("  st1 { %s.1d }, [x.st], #8" % ln(i))
    L += ["  .restore all", "  ret", ".end"]
    return L
out = ["// GENERATED by asm/gen_keccak_absorb.py -- do not edit by hand."]
for W in RATES: out += kernel(W) + [""]
open(sys.argv[1] if len(sys.argv)>1 else "asm/keccak_absorb.asm","w").write("\n".join(out)+"\n")
print("wrote kernels for rates", RATES)
