#!/usr/bin/env python3
# Generate an asmp (.asm) CIOS Montgomery multiply, drop-in for the C
#   static void mont_mul(u64 r[4], u64 a[4], u64 b[4], const mont_ctx *ctx)
# ctx layout: m[0..3] at offset 0, n0 at offset 32 (see mont_ctx in p256.c).
# Fully register-resident, fully unrolled. Faithful translation of the C loop:
#   for i: t += a[i]*b ;  mm=t[0]*n0 ;  t += mm*m ;  t >>= 64word
# then one constant-time conditional subtract of m.
import sys

L = []
def e(s=""): L.append(s)

e("// GENERATED by gen_montmul.py -- do not edit by hand.")
e("// CIOS Montgomery multiply, drop-in for C mont_mul(r,a,b,ctx).")
e("// ABI: x0=r, x1=a, x2=b, x3=ctx (m[4]@0, n0@32).")
e(".function mont_mul_asm export (")
e("  in: x.r, x.a, x.b, x.ctx")
e(")")
e("entry:")
# load inputs (a[i] loaded lazily per outer iteration to cut register pressure)
for k in range(4): e(f"  ldr x.b{k}, [x.b, #{k*8}]")
for k in range(4): e(f"  ldr x.m{k}, [x.ctx, #{k*8}]")
e("  ldr x.n0, [x.ctx, #32]")
# accumulator t0..t5 = 0
for k in range(6): e(f"  mov x.t{k}, xzr")
e("")

def mac_loop(mult, mregs, tag):
    # t_j = mult*mregs[j] + t_j + carry   for j=0..3 ; then t4+=carry, t5+=carryout
    e(f"  // --- {tag}: t[0..3] += {mult}*R + carry ---")
    e("  mov x.cy, xzr")
    for j in range(4):
        e(f"  mul   x.lo, x.{mult}, x.{mregs[j]}")
        e(f"  umulh x.hi, x.{mult}, x.{mregs[j]}")
        e(f"  adds  x.t{j}, x.t{j}, x.lo")
        e(f"  adc   x.hi, x.hi, xzr")
        e(f"  adds  x.t{j}, x.t{j}, x.cy")
        e(f"  adc   x.cy, x.hi, xzr")
    e("  adds x.t4, x.t4, x.cy")
    e("  adc  x.t5, x.t5, xzr")

for i in range(4):
    e(f"  // ===== outer i={i} =====")
    e(f"  ldr x.ai, [x.a, #{i*8}]")
    mac_loop("ai", [f"b{k}" for k in range(4)], f"i{i} mul-b")
    e(f"  mul x.mm, x.t0, x.n0            // mm = t[0]*n0")
    mac_loop("mm", [f"m{k}" for k in range(4)], f"i{i} reduce")
    # shift down one 64-bit word: t0=t1..t4=t5, t5=0  (t0 was reduced to 0)
    e("  // shift accumulator down one word")
    for k in range(5): e(f"  mov x.t{k}, x.t{k+1}")
    e("  mov x.t5, xzr")
    e("")

# constant-time conditional subtract of m: if (t4!=0 || t0..3>=m) out=t-m else t
e("  // conditional subtract m (constant-time): value = t4:t3:t2:t1:t0")
e("  subs x.s0, x.t0, x.m0")
e("  sbcs x.s1, x.t1, x.m1")
e("  sbcs x.s2, x.t2, x.m2")
e("  sbcs x.s3, x.t3, x.m3")
e("  sbcs xzr, x.t4, xzr            // carry set (cs) iff value >= m")
e("  csel x.o0, x.s0, x.t0, cs")
e("  csel x.o1, x.s1, x.t1, cs")
e("  csel x.o2, x.s2, x.t2, cs")
e("  csel x.o3, x.s3, x.t3, cs")
for k in range(4): e(f"  str x.o{k}, [x.r, #{k*8}]")
e("  ret")
e(".end")

open(sys.argv[1] if len(sys.argv)>1 else "montmul.asm","w").write("\n".join(L)+"\n")
print("wrote", sys.argv[1] if len(sys.argv)>1 else "montmul.asm", f"({len(L)} lines)")
