#!/usr/bin/env python3
# mont_mul_p256 v2: interleaved CIOS Montgomery multiply mod the P-256 prime,
# following OpenSSL ecp_nistz256-armv8's structure. n0=1, so each reduction
# word is pure shift/add: eliminate acc0 with lsl/lsr + subs/sbc + 5 adds,
# keeping the accumulator at 6 words (acc0..acc5) instead of SOS's 8-word
# product. ~120 instructions vs the SOS ~235. ABI: x0=r, x1=a, x2=b.
import sys
L=[]
def e(s=""):L.append(s)

def reduce_step():
    # eliminate acc0 (n0=1): acc = (acc + acc0*p) >> 64
    e("  ubfm x.t0, x.acc0, #32, #31")   # t0 = acc0<<32
    e("  ubfm x.t1, x.acc0, #32, #63")   # t1 = acc0>>32
    e("  subs x.t2, x.acc0, x.t0")
    e("  sbc  x.t3, x.acc0, x.t1")
    e("  adds x.acc0, x.acc1, x.t0")
    e("  adcs x.acc1, x.acc2, x.t1")
    e("  adcs x.acc2, x.acc3, x.t2")
    e("  adcs x.acc3, x.acc4, x.t3")
    e("  adc  x.acc4, x.acc5, xzr")

e("// GENERATED by gen_montmul_p256_cios.py -- do not edit by hand.")
e("// Interleaved CIOS Montgomery multiply mod P-256 prime. ABI: x0=r,x1=a,x2=b.")
e(".function mont_mul_p256 export (")
e("  in: x.r, x.a, x.b")
e(")")
e("entry:")
for k in range(4): e(f"  ldr x.a{k}, [x.a, #{k*8}]")
for k in range(4): e(f"  ldr x.b{k}, [x.b, #{k*8}]")
# ---- b[0]: multiply (no accumulate) ----
e("  // b[0]")
e("  mul   x.acc0, x.a0, x.b0")
e("  umulh x.t0,   x.a0, x.b0")
e("  mul   x.acc1, x.a1, x.b0")
e("  umulh x.t1,   x.a1, x.b0")
e("  mul   x.acc2, x.a2, x.b0")
e("  umulh x.t2,   x.a2, x.b0")
e("  mul   x.acc3, x.a3, x.b0")
e("  umulh x.t3,   x.a3, x.b0")
e("  adds  x.acc1, x.acc1, x.t0")
e("  adcs  x.acc2, x.acc2, x.t1")
e("  adcs  x.acc3, x.acc3, x.t2")
e("  adc   x.acc4, xzr, x.t3")
e("  mov   x.acc5, xzr")
reduce_step()
# ---- b[1..3]: multiply-accumulate ----
for i in range(1,4):
    e(f"  // b[{i}]")
    e(f"  mul x.t0, x.a0, x.b{i}")
    e(f"  mul x.t1, x.a1, x.b{i}")
    e(f"  mul x.t2, x.a2, x.b{i}")
    e(f"  mul x.t3, x.a3, x.b{i}")
    e("  adds x.acc0, x.acc0, x.t0")
    e("  adcs x.acc1, x.acc1, x.t1")
    e("  adcs x.acc2, x.acc2, x.t2")
    e("  adcs x.acc3, x.acc3, x.t3")
    e("  adc  x.acc4, x.acc4, xzr")
    e(f"  umulh x.t0, x.a0, x.b{i}")
    e(f"  umulh x.t1, x.a1, x.b{i}")
    e(f"  umulh x.t2, x.a2, x.b{i}")
    e(f"  umulh x.t3, x.a3, x.b{i}")
    e("  adds x.acc1, x.acc1, x.t0")
    e("  adcs x.acc2, x.acc2, x.t1")
    e("  adcs x.acc3, x.acc3, x.t2")
    e("  adcs x.acc4, x.acc4, x.t3")
    e("  adc  x.acc5, xzr, xzr")
    reduce_step()
# ---- conditional subtract p ; result acc0..acc3 (overflow acc4) ----
e("  movn x.pp0, #0")
e("  movz x.pp1, #0xffff"); e("  movk x.pp1, #0xffff, lsl #16")
e("  movz x.pp3, #0x0001"); e("  movk x.pp3, #0xffff, lsl #32"); e("  movk x.pp3, #0xffff, lsl #48")
e("  subs x.s0, x.acc0, x.pp0")
e("  sbcs x.s1, x.acc1, x.pp1")
e("  sbcs x.s2, x.acc2, xzr")
e("  sbcs x.s3, x.acc3, x.pp3")
e("  sbcs xzr,  x.acc4, xzr")
e("  csel x.o0, x.s0, x.acc0, cs")
e("  csel x.o1, x.s1, x.acc1, cs")
e("  csel x.o2, x.s2, x.acc2, cs")
e("  csel x.o3, x.s3, x.acc3, cs")
for k in range(4): e(f"  str x.o{k}, [x.r, #{k*8}]")
e("  ret")
e(".end")
open(sys.argv[1],"w").write("\n".join(L)+"\n")
print("wrote",sys.argv[1],f"({len(L)} lines)")
