#!/usr/bin/env python3
# mont_mul_asm(r,a,b,ctx): generic interleaved-CIOS Montgomery multiply for an
# arbitrary modulus (used for the P-256 group order n). Reads ctx->m[0..3] and
# ctx->n0 (offset 32). Same interleaved structure as mont_mul_p256 but with the
# generic reduction mm=acc0*n0 ; acc += mm*m ; shift. ABI: x0=r,x1=a,x2=b,x3=ctx.
import sys
L=[]
def e(s=""):L.append(s)

def accumulate(bi_reg):
    # acc[0..3] += a[]*bi (low), acc[1..4] += a[]*bi (high); acc5 = top carry
    for j in range(4): e(f"  mul x.p{j}, x.a{j}, {bi_reg}")
    e("  adds x.acc0, x.acc0, x.p0")
    e("  adcs x.acc1, x.acc1, x.p1")
    e("  adcs x.acc2, x.acc2, x.p2")
    e("  adcs x.acc3, x.acc3, x.p3")
    e("  adc  x.acc4, x.acc4, xzr")
    for j in range(4): e(f"  umulh x.p{j}, x.a{j}, {bi_reg}")
    e("  adds x.acc1, x.acc1, x.p0")
    e("  adcs x.acc2, x.acc2, x.p1")
    e("  adcs x.acc3, x.acc3, x.p2")
    e("  adcs x.acc4, x.acc4, x.p3")
    e("  adc  x.acc5, xzr, xzr")

def reduce():
    # mm = acc0*n0 ; acc += mm*m (acc0 -> 0) ; shift down one word
    e("  mul x.mm, x.acc0, x.n0")
    for j in range(4): e(f"  mul x.p{j}, x.mm, x.m{j}")
    e("  adds x.acc0, x.acc0, x.p0")       # -> 0
    e("  adcs x.acc1, x.acc1, x.p1")
    e("  adcs x.acc2, x.acc2, x.p2")
    e("  adcs x.acc3, x.acc3, x.p3")
    e("  adcs x.acc4, x.acc4, xzr")
    e("  adc  x.acc5, x.acc5, xzr")
    for j in range(4): e(f"  umulh x.p{j}, x.mm, x.m{j}")
    e("  adds x.acc0, x.acc1, x.p0")       # shift: new acc0 = acc1 + hi0
    e("  adcs x.acc1, x.acc2, x.p1")
    e("  adcs x.acc2, x.acc3, x.p2")
    e("  adcs x.acc3, x.acc4, x.p3")
    e("  adc  x.acc4, x.acc5, xzr")

e("// GENERATED by gen_montmul_generic.py -- do not edit by hand.")
e("// Generic interleaved-CIOS Montgomery multiply. ABI: x0=r,x1=a,x2=b,x3=ctx.")
e(".function mont_mul_asm export (")
e("  in: x.r, x.a, x.b, x.ctx")
e(")")
e("entry:")
for k in range(4): e(f"  ldr x.a{k}, [x.a, #{k*8}]")
for k in range(4): e(f"  ldr x.b{k}, [x.b, #{k*8}]")
for k in range(4): e(f"  ldr x.m{k}, [x.ctx, #{k*8}]")
e("  ldr x.n0, [x.ctx, #32]")
# first word b[0]: multiply (no accumulate)
e("  // b[0]")
for j in range(4): e(f"  mul x.acc{j}, x.a{j}, x.b0")
for j in range(4): e(f"  umulh x.p{j}, x.a{j}, x.b0")
e("  adds x.acc1, x.acc1, x.p0")
e("  adcs x.acc2, x.acc2, x.p1")
e("  adcs x.acc3, x.acc3, x.p2")
e("  adc  x.acc4, xzr, x.p3")
e("  mov  x.acc5, xzr")
reduce()
for i in range(1,4):
    e(f"  // b[{i}]")
    accumulate(f"x.b{i}")
    reduce()
# final conditional subtract m (result acc0..acc3, overflow acc4)
e("  subs x.p0, x.acc0, x.m0")
e("  sbcs x.p1, x.acc1, x.m1")
e("  sbcs x.p2, x.acc2, x.m2")
e("  sbcs x.p3, x.acc3, x.m3")
e("  sbcs xzr,  x.acc4, xzr")
e("  csel x.o0, x.p0, x.acc0, cs")
e("  csel x.o1, x.p1, x.acc1, cs")
e("  csel x.o2, x.p2, x.acc2, cs")
e("  csel x.o3, x.p3, x.acc3, cs")
for k in range(4): e(f"  str x.o{k}, [x.r, #{k*8}]")
e("  ret")
e(".end")
open(sys.argv[1],"w").write("\n".join(L)+"\n")
print("wrote",sys.argv[1],f"({len(L)} lines)")
