#!/usr/bin/env python3
# Generate mont_mul_p256(r, a, b): Montgomery multiply mod the P-256 field
# prime p = 2^256 - 2^224 + 2^192 + 2^96 - 1, R = 2^256.
# Drop-in for mont_mul(r,a,b,&FP): same Montgomery domain, hardcoded p.
#
# SOS: full 4x4 schoolbook product T[0..7] = a*b, then Montgomery reduction
# exploiting n0 = -p^-1 mod 2^64 = 1 and p's Solinas limb structure
#   p0 = 2^64-1, p1 = 2^32-1, p2 = 0, p3 = 2^64-2^32+1
# so each reduction word u=T[i] contributes u*p via shifts/subtracts, no mul.
import sys
L=[]
def e(s=""):L.append(s)

e("// GENERATED by gen_montmul_p256.py -- do not edit by hand.")
e("// Montgomery multiply mod P-256 field prime p. ABI: x0=r, x1=a, x2=b.")
e(".function mont_mul_p256 export (")
e("  in: x.r, x.a, x.b")
e(")")
e("entry:")
for k in range(4): e(f"  ldr x.b{k}, [x.b, #{k*8}]")
# T0..T3 = 0 (T4..T7 first-written by carry mov)
for k in range(4): e(f"  mov x.T{k}, xzr")
e("  // ---- schoolbook product T[0..7] = a*b (operand scanning) ----")
for i in range(4):
    e(f"  ldr x.ai, [x.a, #{i*8}]")
    e("  mov x.C, xzr")
    for j in range(4):
        w=i+j
        e(f"  mul   x.lo, x.ai, x.b{j}")
        e(f"  umulh x.hi, x.ai, x.b{j}")
        e(f"  adds  x.T{w}, x.T{w}, x.lo")
        e(f"  adc   x.hi, x.hi, xzr")
        e(f"  adds  x.T{w}, x.T{w}, x.C")
        e(f"  adc   x.C, x.hi, xzr")
    e(f"  mov x.T{i+4}, x.C")
e("  mov x.T8, xzr")
e("  // ---- Montgomery reduction mod p (n0=1, shift-based u*p) ----")
for i in range(4):
    e(f"  // reduce word {i}: u = T[{i}]")
    e(f"  mov x.u, x.T{i}")
    e("  ubfm x.ush, x.u, #32, #31")   # lsl #32
    e("  ubfm x.uhi, x.u, #32, #63")   # lsr #32
    # u*p0 = {hi0=u-(u!=0), lo0=-u}
    e("  subs x.lo0, xzr, x.u")            # lo0 = -u ; C=1 iff u==0
    e("  sbc  x.hi0, x.u, xzr")            # hi0 = u-(1-C) = u-(u!=0)
    # u*p1 = {hi1, lo1=(u<<32)-u}
    e("  subs x.lo1, x.ush, x.u")          # C=1 iff ush>=u
    e("  sbc  x.hi1, x.uhi, xzr")          # hi1 = uhi-(u>ush)
    # u*p3 = (u<<64)-(u<<32)+u = {hi3, lo3}
    e("  subs x.Dlo, xzr, x.ush")          # -(u<<32)
    e("  sbc  x.Dhi, x.u, x.uhi")          # u-(u>>32)-(ush>0)
    e("  adds x.lo3, x.Dlo, x.u")          # u-(u<<32)
    e("  adc  x.hi3, x.Dhi, xzr")
    # V = {lo0, hi0+lo1, hi1, lo3, hi3} with internal carry
    e("  adds x.v1, x.hi0, x.lo1")
    e("  adcs x.v2, x.hi1, xzr")
    e("  adcs x.v3, x.lo3, xzr")
    e("  adc  x.v4, x.hi3, xzr")
    # add V to T[i..i+4], ripple carry up to T8
    e(f"  adds x.T{i},   x.T{i},   x.lo0")   # -> 0
    e(f"  adcs x.T{i+1}, x.T{i+1}, x.v1")
    e(f"  adcs x.T{i+2}, x.T{i+2}, x.v2")
    e(f"  adcs x.T{i+3}, x.T{i+3}, x.v3")
    e(f"  adcs x.T{i+4}, x.T{i+4}, x.v4")
    hi = list(range(i+5, 9))               # ripple targets up to T8
    for idx,w in enumerate(hi):
        op = "adc" if idx==len(hi)-1 else "adcs"
        e(f"  {op}  x.T{w}, x.T{w}, xzr")
e("  // ---- result = T4..T7 (overflow T8); conditional subtract p ----")
# p limbs: p0=0xffffffffffffffff, p1=0x00000000ffffffff, p2=0, p3=0xffffffff00000001
e("  movn x.p0, #0")                         # 0xffffffffffffffff
e("  movz x.p1, #0xffff")                    # 0x00000000ffffffff
e("  movk x.p1, #0xffff, lsl #16")
e("  movz x.p3, #0x0001")                    # 0xffffffff00000001
e("  movk x.p3, #0xffff, lsl #32")
e("  movk x.p3, #0xffff, lsl #48")
e("  subs x.s0, x.T4, x.p0")
e("  sbcs x.s1, x.T5, x.p1")
e("  sbcs x.s2, x.T6, xzr")                 # p2 = 0
e("  sbcs x.s3, x.T7, x.p3")
e("  sbcs xzr,  x.T8, xzr")                 # carry set iff value >= p
e("  csel x.o0, x.s0, x.T4, cs")
e("  csel x.o1, x.s1, x.T5, cs")
e("  csel x.o2, x.s2, x.T6, cs")
e("  csel x.o3, x.s3, x.T7, cs")
for k in range(4): e(f"  str x.o{k}, [x.r, #{k*8}]")
e("  ret")
e(".end")
open(sys.argv[1],"w").write("\n".join(L)+"\n")
print("wrote",sys.argv[1],f"({len(L)} lines)")
