#!/usr/bin/env python3
# Generate mont_sqr_p256(r, a): Montgomery square mod the P-256 field prime.
# Symmetric product a^2 = sum_i a_i^2 << 128i  +  2*sum_{i<j} a_i a_j << 64(i+j)
# (6 off-diagonal muls instead of the schoolbook's extra 6), then the same
# shift-based Montgomery reduction as mont_mul_p256. Drop-in for mont_mul(r,a,a,&FP).
import sys
L=[]
def e(s=""):L.append(s)

def reduction():
    # identical to gen_montmul_p256: reduce T[0..7] (+T8) mod p, n0=1, shift-based
    e("  mov x.T8, xzr")
    e("  // ---- Montgomery reduction mod p (n0=1, shift-based u*p) ----")
    for i in range(4):
        e(f"  mov x.u, x.T{i}")
        e("  ubfm x.ush, x.u, #32, #31")   # lsl #32
        e("  ubfm x.uhi, x.u, #32, #63")   # lsr #32
        e("  subs x.lo0, xzr, x.u")
        e("  sbc  x.hi0, x.u, xzr")
        e("  subs x.lo1, x.ush, x.u")
        e("  sbc  x.hi1, x.uhi, xzr")
        e("  subs x.Dlo, xzr, x.ush")
        e("  sbc  x.Dhi, x.u, x.uhi")
        e("  adds x.lo3, x.Dlo, x.u")
        e("  adc  x.hi3, x.Dhi, xzr")
        e("  adds x.v1, x.hi0, x.lo1")
        e("  adcs x.v2, x.hi1, xzr")
        e("  adcs x.v3, x.lo3, xzr")
        e("  adc  x.v4, x.hi3, xzr")
        e(f"  adds x.T{i},   x.T{i},   x.lo0")
        e(f"  adcs x.T{i+1}, x.T{i+1}, x.v1")
        e(f"  adcs x.T{i+2}, x.T{i+2}, x.v2")
        e(f"  adcs x.T{i+3}, x.T{i+3}, x.v3")
        e(f"  adcs x.T{i+4}, x.T{i+4}, x.v4")
        hi=list(range(i+5,9))
        for idx,w in enumerate(hi):
            op="adc" if idx==len(hi)-1 else "adcs"
            e(f"  {op}  x.T{w}, x.T{w}, xzr")
    e("  // ---- conditional subtract p ----")
    e("  movn x.p0, #0")
    e("  movz x.p1, #0xffff"); e("  movk x.p1, #0xffff, lsl #16")
    e("  movz x.p3, #0x0001"); e("  movk x.p3, #0xffff, lsl #32"); e("  movk x.p3, #0xffff, lsl #48")
    e("  subs x.s0, x.T4, x.p0")
    e("  sbcs x.s1, x.T5, x.p1")
    e("  sbcs x.s2, x.T6, xzr")
    e("  sbcs x.s3, x.T7, x.p3")
    e("  sbcs xzr,  x.T8, xzr")
    e("  csel x.o0, x.s0, x.T4, cs")
    e("  csel x.o1, x.s1, x.T5, cs")
    e("  csel x.o2, x.s2, x.T6, cs")
    e("  csel x.o3, x.s3, x.T7, cs")
    for k in range(4): e(f"  str x.o{k}, [x.r, #{k*8}]")

e("// GENERATED by gen_montsqr_p256.py -- do not edit by hand.")
e("// Montgomery square mod P-256 field prime. ABI: x0=r, x1=a.")
e(".function mont_sqr_p256 export (")
e("  in: x.r, x.a")
e(")")
e("entry:")
for k in range(4): e(f"  ldr x.a{k}, [x.a, #{k*8}]")
for k in range(8): e(f"  mov x.T{k}, xzr")
e("  // ---- off-diagonal sum: T += a_i*a_j (i<j) at word i+j ----")
pairs=[(0,1),(0,2),(0,3),(1,2),(1,3),(2,3)]
for (i,j) in pairs:
    w=i+j
    e(f"  mul   x.lo, x.a{i}, x.a{j}")
    e(f"  umulh x.hi, x.a{i}, x.a{j}")
    e(f"  adds  x.T{w},   x.T{w},   x.lo")
    e(f"  adcs  x.T{w+1}, x.T{w+1}, x.hi")
    for k in range(w+2,8):
        op="adc" if k==7 else "adcs"
        e(f"  {op}  x.T{k}, x.T{k}, xzr")
e("  // ---- double the off-diagonal sum: T = 2*T ----")
e("  adds x.T0, x.T0, x.T0")
for k in range(1,8):
    op="adc" if k==7 else "adcs"
    e(f"  {op}  x.T{k}, x.T{k}, x.T{k}")
e("  // ---- add diagonal a_i^2 at word 2i ----")
for i in range(4):
    w=2*i
    e(f"  mul   x.lo, x.a{i}, x.a{i}")
    e(f"  umulh x.hi, x.a{i}, x.a{i}")
    e(f"  adds  x.T{w},   x.T{w},   x.lo")
    e(f"  adcs  x.T{w+1}, x.T{w+1}, x.hi")
    for k in range(w+2,8):
        op="adc" if k==7 else "adcs"
        e(f"  {op}  x.T{k}, x.T{k}, xzr")
reduction()
e("  ret")
e(".end")
open(sys.argv[1],"w").write("\n".join(L)+"\n")
print("wrote",sys.argv[1],f"({len(L)} lines)")
