#!/usr/bin/env python3
# Streaming CIOS Montgomery multiply, width K. Accumulator acc[0..K+1] stays in
# registers across the whole routine (never spilled to stack -- clang's k=16/32
# bottleneck); operands a[]/m[] are loaded on demand, and each product is added
# with a serial single-word MAC (one lo/hi/carry temp), so register pressure is
# ~K+2 (acc) + a handful, fitting k=16 without spilling.
# ABI: x0=r, x1=a, x2=b, x3=m, x4=n0.
import sys
K=int(sys.argv[1]); out=sys.argv[2]
L=[]; e=lambda s="":L.append(s)

def mac_row(src_ptr, factor):    # acc[0..K-1] += src[j]*factor ; carry -> acc[K],acc[K+1]
    e("  mov x.carry, xzr")
    for j in range(K):
        e(f"  ldr x.tmp, [{src_ptr}, #{j*8}]")
        e(f"  mul x.lo, x.tmp, {factor}")
        e(f"  umulh x.hi, x.tmp, {factor}")
        e(f"  adds x.acc{j}, x.acc{j}, x.lo")
        e("  adc x.hi, x.hi, xzr")
        e(f"  adds x.acc{j}, x.acc{j}, x.carry")
        e("  adc x.carry, x.hi, xzr")
    e(f"  adds x.acc{K}, x.acc{K}, x.carry")
    e(f"  adc x.acc{K+1}, x.acc{K+1}, xzr")

def reduce():
    e("  mul x.mm, x.acc0, x.n0")
    e("  mov x.carry, xzr")
    for j in range(K):
        e(f"  ldr x.tmp, [x.m, #{j*8}]")
        e(f"  mul x.lo, x.tmp, x.mm")
        e(f"  umulh x.hi, x.tmp, x.mm")
        e(f"  adds x.acc{j}, x.acc{j}, x.lo")
        e("  adc x.hi, x.hi, xzr")
        e(f"  adds x.acc{j}, x.acc{j}, x.carry")
        e("  adc x.carry, x.hi, xzr")
    e(f"  adds x.acc{K}, x.acc{K}, x.carry")
    e(f"  adc x.acc{K+1}, x.acc{K+1}, xzr")
    # shift down one word: acc[j] <- acc[j+1]  (acc0 was driven to 0)
    for j in range(K+1): e(f"  mov x.acc{j}, x.acc{j+1}")
    e(f"  mov x.acc{K+1}, xzr")

e(f"// GENERATED by gen_montmul_stream.py K={K} -- do not edit.")
e(f".function bn_mul_mont_k{K} export (")
e("  in: x.r, x.a, x.b, x.m, x.n0")
e(")")
e("entry:")
e("  .save all")
for j in range(K+2): e(f"  mov x.acc{j}, xzr")
e("  mov x.bi_i, xzr")     # loop counter not used; fully unrolled over b[i]
for i in range(K):
    e(f"  // b[{i}]")
    e(f"  ldr x.bi, [x.b, #{i*8}]")
    mac_row("x.a", "x.bi")
    reduce()
# conditional subtract m
e("  subs x.o0, x.acc0, xzr")   # placeholder to seed flags? do explicit
e("  mov x.borrow, xzr")
for j in range(K):
    e(f"  ldr x.tmp, [x.m, #{j*8}]")
    if j==0: e(f"  subs x.s{j}, x.acc{j}, x.tmp")
    else:    e(f"  sbcs x.s{j}, x.acc{j}, x.tmp")
e(f"  sbcs xzr, x.acc{K}, xzr")
for j in range(K): e(f"  csel x.o{j}, x.s{j}, x.acc{j}, cs")
for j in range(K): e(f"  str x.o{j}, [x.r, #{j*8}]")
e("  .restore all")
e("  ret")
e(".end")
open(out,"w").write("\n".join(L)+"\n")
print("wrote",out,f"K={K} ({len(L)} lines)")
