;; 2-way batched Keccak-f[1600] (lane-major interleaved: st[2i]=lane0 word i,
;; st[2i+1]=lane1 word i). One call runs a full 24-round permutation on both
;; lanes via eor3/rax1/xar/bcax. ~62 ns/lane. Routed from SLH-DSA (rktcrypto_slhdsa.c).
  // GENERATED by asm/gen/keccak.rkt f2 -- do not edit by hand.
.function keccak_f2_asm export (
  in: x.st, x.rc
)
entry:
  .save all
  ld1 { v.ln0.2d }, [x.st], #16
  ld1 { v.ln1.2d }, [x.st], #16
  ld1 { v.ln2.2d }, [x.st], #16
  ld1 { v.ln3.2d }, [x.st], #16
  ld1 { v.ln4.2d }, [x.st], #16
  ld1 { v.ln5.2d }, [x.st], #16
  ld1 { v.ln6.2d }, [x.st], #16
  ld1 { v.ln7.2d }, [x.st], #16
  ld1 { v.ln8.2d }, [x.st], #16
  ld1 { v.ln9.2d }, [x.st], #16
  ld1 { v.ln10.2d }, [x.st], #16
  ld1 { v.ln11.2d }, [x.st], #16
  ld1 { v.ln12.2d }, [x.st], #16
  ld1 { v.ln13.2d }, [x.st], #16
  ld1 { v.ln14.2d }, [x.st], #16
  ld1 { v.ln15.2d }, [x.st], #16
  ld1 { v.ln16.2d }, [x.st], #16
  ld1 { v.ln17.2d }, [x.st], #16
  ld1 { v.ln18.2d }, [x.st], #16
  ld1 { v.ln19.2d }, [x.st], #16
  ld1 { v.ln20.2d }, [x.st], #16
  ld1 { v.ln21.2d }, [x.st], #16
  ld1 { v.ln22.2d }, [x.st], #16
  ld1 { v.ln23.2d }, [x.st], #16
  ld1 { v.ln24.2d }, [x.st], #16
  sub x.st, x.st, #400
  mov x.i, xzr
round:
  eor3 v.t0.16b, v.ln0.16b, v.ln5.16b, v.ln10.16b
  eor3 v.t0.16b, v.t0.16b, v.ln15.16b, v.ln20.16b
  eor3 v.t1.16b, v.ln1.16b, v.ln6.16b, v.ln11.16b
  eor3 v.t1.16b, v.t1.16b, v.ln16.16b, v.ln21.16b
  eor3 v.t2.16b, v.ln2.16b, v.ln7.16b, v.ln12.16b
  eor3 v.t2.16b, v.t2.16b, v.ln17.16b, v.ln22.16b
  eor3 v.t3.16b, v.ln3.16b, v.ln8.16b, v.ln13.16b
  eor3 v.t3.16b, v.t3.16b, v.ln18.16b, v.ln23.16b
  eor3 v.t4.16b, v.ln4.16b, v.ln9.16b, v.ln14.16b
  eor3 v.t4.16b, v.t4.16b, v.ln19.16b, v.ln24.16b
  rax1 v.t5.2d, v.t4.2d, v.t1.2d
  rax1 v.t6.2d, v.t0.2d, v.t2.2d
  rax1 v.t1.2d, v.t1.2d, v.t3.2d
  rax1 v.t2.2d, v.t2.2d, v.t4.2d
  rax1 v.t3.2d, v.t3.2d, v.t0.2d
  eor v.ln0.16b, v.ln0.16b, v.t5.16b
  mov v.t0.16b, v.ln1.16b
  xar v.ln1.2d, v.ln6.2d, v.t6.2d, #20
  xar v.ln6.2d, v.ln9.2d, v.t3.2d, #44
  xar v.ln9.2d, v.ln22.2d, v.t1.2d, #3
  xar v.ln22.2d, v.ln14.2d, v.t3.2d, #25
  xar v.ln14.2d, v.ln20.2d, v.t5.2d, #46
  xar v.ln20.2d, v.ln2.2d, v.t1.2d, #2
  xar v.ln2.2d, v.ln12.2d, v.t1.2d, #21
  xar v.ln12.2d, v.ln13.2d, v.t2.2d, #39
  xar v.ln13.2d, v.ln19.2d, v.t3.2d, #56
  xar v.ln19.2d, v.ln23.2d, v.t2.2d, #8
  xar v.ln23.2d, v.ln15.2d, v.t5.2d, #23
  xar v.ln15.2d, v.ln4.2d, v.t3.2d, #37
  xar v.ln4.2d, v.ln24.2d, v.t3.2d, #50
  xar v.ln24.2d, v.ln21.2d, v.t6.2d, #62
  xar v.ln21.2d, v.ln8.2d, v.t2.2d, #9
  xar v.ln8.2d, v.ln16.2d, v.t6.2d, #19
  xar v.ln16.2d, v.ln5.2d, v.t5.2d, #28
  xar v.ln5.2d, v.ln3.2d, v.t2.2d, #36
  xar v.ln3.2d, v.ln18.2d, v.t2.2d, #43
  xar v.ln18.2d, v.ln17.2d, v.t1.2d, #49
  xar v.ln17.2d, v.ln11.2d, v.t6.2d, #54
  xar v.ln11.2d, v.ln7.2d, v.t1.2d, #58
  xar v.ln7.2d, v.ln10.2d, v.t5.2d, #61
  xar v.ln10.2d, v.t0.2d, v.t6.2d, #63
  mov v.t5.16b, v.ln0.16b
  mov v.t6.16b, v.ln1.16b
  bcax v.ln0.16b, v.t5.16b, v.ln2.16b, v.t6.16b
  bcax v.ln1.16b, v.t6.16b, v.ln3.16b, v.ln2.16b
  bcax v.ln2.16b, v.ln2.16b, v.ln4.16b, v.ln3.16b
  bcax v.ln3.16b, v.ln3.16b, v.t5.16b, v.ln4.16b
  bcax v.ln4.16b, v.ln4.16b, v.t6.16b, v.t5.16b
  mov v.t5.16b, v.ln5.16b
  mov v.t6.16b, v.ln6.16b
  bcax v.ln5.16b, v.t5.16b, v.ln7.16b, v.t6.16b
  bcax v.ln6.16b, v.t6.16b, v.ln8.16b, v.ln7.16b
  bcax v.ln7.16b, v.ln7.16b, v.ln9.16b, v.ln8.16b
  bcax v.ln8.16b, v.ln8.16b, v.t5.16b, v.ln9.16b
  bcax v.ln9.16b, v.ln9.16b, v.t6.16b, v.t5.16b
  mov v.t5.16b, v.ln10.16b
  mov v.t6.16b, v.ln11.16b
  bcax v.ln10.16b, v.t5.16b, v.ln12.16b, v.t6.16b
  bcax v.ln11.16b, v.t6.16b, v.ln13.16b, v.ln12.16b
  bcax v.ln12.16b, v.ln12.16b, v.ln14.16b, v.ln13.16b
  bcax v.ln13.16b, v.ln13.16b, v.t5.16b, v.ln14.16b
  bcax v.ln14.16b, v.ln14.16b, v.t6.16b, v.t5.16b
  mov v.t5.16b, v.ln15.16b
  mov v.t6.16b, v.ln16.16b
  bcax v.ln15.16b, v.t5.16b, v.ln17.16b, v.t6.16b
  bcax v.ln16.16b, v.t6.16b, v.ln18.16b, v.ln17.16b
  bcax v.ln17.16b, v.ln17.16b, v.ln19.16b, v.ln18.16b
  bcax v.ln18.16b, v.ln18.16b, v.t5.16b, v.ln19.16b
  bcax v.ln19.16b, v.ln19.16b, v.t6.16b, v.t5.16b
  mov v.t5.16b, v.ln20.16b
  mov v.t6.16b, v.ln21.16b
  bcax v.ln20.16b, v.t5.16b, v.ln22.16b, v.t6.16b
  bcax v.ln21.16b, v.t6.16b, v.ln23.16b, v.ln22.16b
  bcax v.ln22.16b, v.ln22.16b, v.ln24.16b, v.ln23.16b
  bcax v.ln23.16b, v.ln23.16b, v.t5.16b, v.ln24.16b
  bcax v.ln24.16b, v.ln24.16b, v.t6.16b, v.t5.16b
  add x.rcp, x.rc, x.i
  ld1r { v.t0.2d }, [x.rcp]
  eor v.ln0.16b, v.ln0.16b, v.t0.16b
  add x.i, x.i, #8
  cmp x.i, #192
  b.lt round
  st1 { v.ln0.2d }, [x.st], #16
  st1 { v.ln1.2d }, [x.st], #16
  st1 { v.ln2.2d }, [x.st], #16
  st1 { v.ln3.2d }, [x.st], #16
  st1 { v.ln4.2d }, [x.st], #16
  st1 { v.ln5.2d }, [x.st], #16
  st1 { v.ln6.2d }, [x.st], #16
  st1 { v.ln7.2d }, [x.st], #16
  st1 { v.ln8.2d }, [x.st], #16
  st1 { v.ln9.2d }, [x.st], #16
  st1 { v.ln10.2d }, [x.st], #16
  st1 { v.ln11.2d }, [x.st], #16
  st1 { v.ln12.2d }, [x.st], #16
  st1 { v.ln13.2d }, [x.st], #16
  st1 { v.ln14.2d }, [x.st], #16
  st1 { v.ln15.2d }, [x.st], #16
  st1 { v.ln16.2d }, [x.st], #16
  st1 { v.ln17.2d }, [x.st], #16
  st1 { v.ln18.2d }, [x.st], #16
  st1 { v.ln19.2d }, [x.st], #16
  st1 { v.ln20.2d }, [x.st], #16
  st1 { v.ln21.2d }, [x.st], #16
  st1 { v.ln22.2d }, [x.st], #16
  st1 { v.ln23.2d }, [x.st], #16
  st1 { v.ln24.2d }, [x.st], #16
  .restore all
  ret
.end

