// GENERATED by gen_montmul.py -- do not edit by hand.
// CIOS Montgomery multiply, drop-in for C mont_mul(r,a,b,ctx).
// ABI: x0=r, x1=a, x2=b, x3=ctx (m[4]@0, n0@32).
.function mont_mul_asm export (
  in: x.r, x.a, x.b, x.ctx
)
entry:
  ldr x.b0, [x.b, #0]
  ldr x.b1, [x.b, #8]
  ldr x.b2, [x.b, #16]
  ldr x.b3, [x.b, #24]
  ldr x.m0, [x.ctx, #0]
  ldr x.m1, [x.ctx, #8]
  ldr x.m2, [x.ctx, #16]
  ldr x.m3, [x.ctx, #24]
  ldr x.n0, [x.ctx, #32]
  mov x.t0, xzr
  mov x.t1, xzr
  mov x.t2, xzr
  mov x.t3, xzr
  mov x.t4, xzr
  mov x.t5, xzr

  // ===== outer i=0 =====
  ldr x.ai, [x.a, #0]
  // --- i0 mul-b: t[0..3] += ai*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  mul x.mm, x.t0, x.n0            // mm = t[0]*n0
  // --- i0 reduce: t[0..3] += mm*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.mm, x.m0
  umulh x.hi, x.mm, x.m0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m1
  umulh x.hi, x.mm, x.m1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m2
  umulh x.hi, x.mm, x.m2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m3
  umulh x.hi, x.mm, x.m3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  // shift accumulator down one word
  mov x.t0, x.t1
  mov x.t1, x.t2
  mov x.t2, x.t3
  mov x.t3, x.t4
  mov x.t4, x.t5
  mov x.t5, xzr

  // ===== outer i=1 =====
  ldr x.ai, [x.a, #8]
  // --- i1 mul-b: t[0..3] += ai*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  mul x.mm, x.t0, x.n0            // mm = t[0]*n0
  // --- i1 reduce: t[0..3] += mm*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.mm, x.m0
  umulh x.hi, x.mm, x.m0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m1
  umulh x.hi, x.mm, x.m1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m2
  umulh x.hi, x.mm, x.m2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m3
  umulh x.hi, x.mm, x.m3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  // shift accumulator down one word
  mov x.t0, x.t1
  mov x.t1, x.t2
  mov x.t2, x.t3
  mov x.t3, x.t4
  mov x.t4, x.t5
  mov x.t5, xzr

  // ===== outer i=2 =====
  ldr x.ai, [x.a, #16]
  // --- i2 mul-b: t[0..3] += ai*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  mul x.mm, x.t0, x.n0            // mm = t[0]*n0
  // --- i2 reduce: t[0..3] += mm*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.mm, x.m0
  umulh x.hi, x.mm, x.m0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m1
  umulh x.hi, x.mm, x.m1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m2
  umulh x.hi, x.mm, x.m2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m3
  umulh x.hi, x.mm, x.m3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  // shift accumulator down one word
  mov x.t0, x.t1
  mov x.t1, x.t2
  mov x.t2, x.t3
  mov x.t3, x.t4
  mov x.t4, x.t5
  mov x.t5, xzr

  // ===== outer i=3 =====
  ldr x.ai, [x.a, #24]
  // --- i3 mul-b: t[0..3] += ai*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  mul x.mm, x.t0, x.n0            // mm = t[0]*n0
  // --- i3 reduce: t[0..3] += mm*R + carry ---
  mov x.cy, xzr
  mul   x.lo, x.mm, x.m0
  umulh x.hi, x.mm, x.m0
  adds  x.t0, x.t0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t0, x.t0, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m1
  umulh x.hi, x.mm, x.m1
  adds  x.t1, x.t1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t1, x.t1, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m2
  umulh x.hi, x.mm, x.m2
  adds  x.t2, x.t2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t2, x.t2, x.cy
  adc   x.cy, x.hi, xzr
  mul   x.lo, x.mm, x.m3
  umulh x.hi, x.mm, x.m3
  adds  x.t3, x.t3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.t3, x.t3, x.cy
  adc   x.cy, x.hi, xzr
  adds x.t4, x.t4, x.cy
  adc  x.t5, x.t5, xzr
  // shift accumulator down one word
  mov x.t0, x.t1
  mov x.t1, x.t2
  mov x.t2, x.t3
  mov x.t3, x.t4
  mov x.t4, x.t5
  mov x.t5, xzr

  // conditional subtract m (constant-time): value = t4:t3:t2:t1:t0
  subs x.s0, x.t0, x.m0
  sbcs x.s1, x.t1, x.m1
  sbcs x.s2, x.t2, x.m2
  sbcs x.s3, x.t3, x.m3
  sbcs xzr, x.t4, xzr            // carry set (cs) iff value >= m
  csel x.o0, x.s0, x.t0, cs
  csel x.o1, x.s1, x.t1, cs
  csel x.o2, x.s2, x.t2, cs
  csel x.o3, x.s3, x.t3, cs
  str x.o0, [x.r, #0]
  str x.o1, [x.r, #8]
  str x.o2, [x.r, #16]
  str x.o3, [x.r, #24]
  ret
.end
