// GENERATED by gen_montmul_generic.py -- do not edit by hand.
// Generic interleaved-CIOS Montgomery multiply. ABI: x0=r,x1=a,x2=b,x3=ctx.
//
// `.save all`: this kernel keeps a[]/b[]/m[]/n0 + a 6-word accumulator live
// (~19 GPRs > the 16 caller-saved). Without a save directive asmp treats the
// leaf as scratch-only (caller-saved colours) and spills the overflow to NEON
// -- an `fmov x,d` before every mul (~64 of them, 2x slowdown). Declaring
// `.save all` unlocks callee-saved GPR allocation, so the overflow lands in
// x19-x26 (saved once in the prologue, zero per-use cost) exactly like
// OpenSSL's ord_mul_mont. Result: 0 fmov, ~14.2 -> ~11.5 ns/op (n/p 1.95 ->
// 1.58x), directly speeding ECDSA scn_inv (mod-n Fermat inverse).
.function mont_mul_asm export (
  in: x.r, x.a, x.b, x.ctx
)
entry:
  .save all
  ldr x.a0, [x.a, #0]
  ldr x.a1, [x.a, #8]
  ldr x.a2, [x.a, #16]
  ldr x.a3, [x.a, #24]
  ldr x.b0, [x.b, #0]
  ldr x.b1, [x.b, #8]
  ldr x.b2, [x.b, #16]
  ldr x.b3, [x.b, #24]
  ldr x.m0, [x.ctx, #0]
  ldr x.m1, [x.ctx, #8]
  ldr x.m2, [x.ctx, #16]
  ldr x.m3, [x.ctx, #24]
  ldr x.n0, [x.ctx, #32]
  // b[0]
  mul x.acc0, x.a0, x.b0
  mul x.acc1, x.a1, x.b0
  mul x.acc2, x.a2, x.b0
  mul x.acc3, x.a3, x.b0
  umulh x.p0, x.a0, x.b0
  umulh x.p1, x.a1, x.b0
  umulh x.p2, x.a2, x.b0
  umulh x.p3, x.a3, x.b0
  adds x.acc1, x.acc1, x.p0
  adcs x.acc2, x.acc2, x.p1
  adcs x.acc3, x.acc3, x.p2
  adc  x.acc4, xzr, x.p3
  mov  x.acc5, xzr
  mul x.mm, x.acc0, x.n0
  mul x.p0, x.mm, x.m0
  mul x.p1, x.mm, x.m1
  mul x.p2, x.mm, x.m2
  mul x.p3, x.mm, x.m3
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  umulh x.p0, x.mm, x.m0
  umulh x.p1, x.mm, x.m1
  umulh x.p2, x.mm, x.m2
  umulh x.p3, x.mm, x.m3
  adds x.acc0, x.acc1, x.p0
  adcs x.acc1, x.acc2, x.p1
  adcs x.acc2, x.acc3, x.p2
  adcs x.acc3, x.acc4, x.p3
  adc  x.acc4, x.acc5, xzr
  // b[1]
  mul x.p0, x.a0, x.b1
  mul x.p1, x.a1, x.b1
  mul x.p2, x.a2, x.b1
  mul x.p3, x.a3, x.b1
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adc  x.acc4, x.acc4, xzr
  umulh x.p0, x.a0, x.b1
  umulh x.p1, x.a1, x.b1
  umulh x.p2, x.a2, x.b1
  umulh x.p3, x.a3, x.b1
  adds x.acc1, x.acc1, x.p0
  adcs x.acc2, x.acc2, x.p1
  adcs x.acc3, x.acc3, x.p2
  adcs x.acc4, x.acc4, x.p3
  adc  x.acc5, xzr, xzr
  mul x.mm, x.acc0, x.n0
  mul x.p0, x.mm, x.m0
  mul x.p1, x.mm, x.m1
  mul x.p2, x.mm, x.m2
  mul x.p3, x.mm, x.m3
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  umulh x.p0, x.mm, x.m0
  umulh x.p1, x.mm, x.m1
  umulh x.p2, x.mm, x.m2
  umulh x.p3, x.mm, x.m3
  adds x.acc0, x.acc1, x.p0
  adcs x.acc1, x.acc2, x.p1
  adcs x.acc2, x.acc3, x.p2
  adcs x.acc3, x.acc4, x.p3
  adc  x.acc4, x.acc5, xzr
  // b[2]
  mul x.p0, x.a0, x.b2
  mul x.p1, x.a1, x.b2
  mul x.p2, x.a2, x.b2
  mul x.p3, x.a3, x.b2
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adc  x.acc4, x.acc4, xzr
  umulh x.p0, x.a0, x.b2
  umulh x.p1, x.a1, x.b2
  umulh x.p2, x.a2, x.b2
  umulh x.p3, x.a3, x.b2
  adds x.acc1, x.acc1, x.p0
  adcs x.acc2, x.acc2, x.p1
  adcs x.acc3, x.acc3, x.p2
  adcs x.acc4, x.acc4, x.p3
  adc  x.acc5, xzr, xzr
  mul x.mm, x.acc0, x.n0
  mul x.p0, x.mm, x.m0
  mul x.p1, x.mm, x.m1
  mul x.p2, x.mm, x.m2
  mul x.p3, x.mm, x.m3
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  umulh x.p0, x.mm, x.m0
  umulh x.p1, x.mm, x.m1
  umulh x.p2, x.mm, x.m2
  umulh x.p3, x.mm, x.m3
  adds x.acc0, x.acc1, x.p0
  adcs x.acc1, x.acc2, x.p1
  adcs x.acc2, x.acc3, x.p2
  adcs x.acc3, x.acc4, x.p3
  adc  x.acc4, x.acc5, xzr
  // b[3]
  mul x.p0, x.a0, x.b3
  mul x.p1, x.a1, x.b3
  mul x.p2, x.a2, x.b3
  mul x.p3, x.a3, x.b3
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adc  x.acc4, x.acc4, xzr
  umulh x.p0, x.a0, x.b3
  umulh x.p1, x.a1, x.b3
  umulh x.p2, x.a2, x.b3
  umulh x.p3, x.a3, x.b3
  adds x.acc1, x.acc1, x.p0
  adcs x.acc2, x.acc2, x.p1
  adcs x.acc3, x.acc3, x.p2
  adcs x.acc4, x.acc4, x.p3
  adc  x.acc5, xzr, xzr
  mul x.mm, x.acc0, x.n0
  mul x.p0, x.mm, x.m0
  mul x.p1, x.mm, x.m1
  mul x.p2, x.mm, x.m2
  mul x.p3, x.mm, x.m3
  adds x.acc0, x.acc0, x.p0
  adcs x.acc1, x.acc1, x.p1
  adcs x.acc2, x.acc2, x.p2
  adcs x.acc3, x.acc3, x.p3
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  umulh x.p0, x.mm, x.m0
  umulh x.p1, x.mm, x.m1
  umulh x.p2, x.mm, x.m2
  umulh x.p3, x.mm, x.m3
  adds x.acc0, x.acc1, x.p0
  adcs x.acc1, x.acc2, x.p1
  adcs x.acc2, x.acc3, x.p2
  adcs x.acc3, x.acc4, x.p3
  adc  x.acc4, x.acc5, xzr
  subs x.p0, x.acc0, x.m0
  sbcs x.p1, x.acc1, x.m1
  sbcs x.p2, x.acc2, x.m2
  sbcs x.p3, x.acc3, x.m3
  sbcs xzr,  x.acc4, xzr
  csel x.o0, x.p0, x.acc0, cs
  csel x.o1, x.p1, x.acc1, cs
  csel x.o2, x.p2, x.acc2, cs
  csel x.o3, x.p3, x.acc3, cs
  str x.o0, [x.r, #0]
  str x.o1, [x.r, #8]
  str x.o2, [x.r, #16]
  str x.o3, [x.r, #24]
  .restore all
  ret
.end
