// GENERATED by gen_montmul_p256.py -- do not edit by hand.
// Montgomery multiply mod P-256 field prime p. ABI: x0=r, x1=a, x2=b.
.function mont_mul_p256 export (
  in: x.r, x.a, x.b
)
entry:
  ldr x.b0, [x.b, #0]
  ldr x.b1, [x.b, #8]
  ldr x.b2, [x.b, #16]
  ldr x.b3, [x.b, #24]
  mov x.T0, xzr
  mov x.T1, xzr
  mov x.T2, xzr
  mov x.T3, xzr
  // ---- schoolbook product T[0..7] = a*b (operand scanning) ----
  ldr x.ai, [x.a, #0]
  mov x.C, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.T0, x.T0, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T0, x.T0, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.T1, x.T1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T1, x.T1, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.T2, x.T2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T2, x.T2, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.T3, x.T3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T3, x.T3, x.C
  adc   x.C, x.hi, xzr
  mov x.T4, x.C
  ldr x.ai, [x.a, #8]
  mov x.C, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.T1, x.T1, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T1, x.T1, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.T2, x.T2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T2, x.T2, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.T3, x.T3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T3, x.T3, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.T4, x.T4, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T4, x.T4, x.C
  adc   x.C, x.hi, xzr
  mov x.T5, x.C
  ldr x.ai, [x.a, #16]
  mov x.C, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.T2, x.T2, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T2, x.T2, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.T3, x.T3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T3, x.T3, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.T4, x.T4, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T4, x.T4, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.T5, x.T5, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T5, x.T5, x.C
  adc   x.C, x.hi, xzr
  mov x.T6, x.C
  ldr x.ai, [x.a, #24]
  mov x.C, xzr
  mul   x.lo, x.ai, x.b0
  umulh x.hi, x.ai, x.b0
  adds  x.T3, x.T3, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T3, x.T3, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b1
  umulh x.hi, x.ai, x.b1
  adds  x.T4, x.T4, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T4, x.T4, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b2
  umulh x.hi, x.ai, x.b2
  adds  x.T5, x.T5, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T5, x.T5, x.C
  adc   x.C, x.hi, xzr
  mul   x.lo, x.ai, x.b3
  umulh x.hi, x.ai, x.b3
  adds  x.T6, x.T6, x.lo
  adc   x.hi, x.hi, xzr
  adds  x.T6, x.T6, x.C
  adc   x.C, x.hi, xzr
  mov x.T7, x.C
  mov x.T8, xzr
  // ---- Montgomery reduction mod p (n0=1, shift-based u*p) ----
  // reduce word 0: u = T[0]
  mov x.u, x.T0
  ubfm x.ush, x.u, #32, #31
  ubfm x.uhi, x.u, #32, #63
  subs x.lo0, xzr, x.u
  sbc  x.hi0, x.u, xzr
  subs x.lo1, x.ush, x.u
  sbc  x.hi1, x.uhi, xzr
  subs x.Dlo, xzr, x.ush
  sbc  x.Dhi, x.u, x.uhi
  adds x.lo3, x.Dlo, x.u
  adc  x.hi3, x.Dhi, xzr
  adds x.v1, x.hi0, x.lo1
  adcs x.v2, x.hi1, xzr
  adcs x.v3, x.lo3, xzr
  adc  x.v4, x.hi3, xzr
  adds x.T0,   x.T0,   x.lo0
  adcs x.T1, x.T1, x.v1
  adcs x.T2, x.T2, x.v2
  adcs x.T3, x.T3, x.v3
  adcs x.T4, x.T4, x.v4
  adcs  x.T5, x.T5, xzr
  adcs  x.T6, x.T6, xzr
  adcs  x.T7, x.T7, xzr
  adc  x.T8, x.T8, xzr
  // reduce word 1: u = T[1]
  mov x.u, x.T1
  ubfm x.ush, x.u, #32, #31
  ubfm x.uhi, x.u, #32, #63
  subs x.lo0, xzr, x.u
  sbc  x.hi0, x.u, xzr
  subs x.lo1, x.ush, x.u
  sbc  x.hi1, x.uhi, xzr
  subs x.Dlo, xzr, x.ush
  sbc  x.Dhi, x.u, x.uhi
  adds x.lo3, x.Dlo, x.u
  adc  x.hi3, x.Dhi, xzr
  adds x.v1, x.hi0, x.lo1
  adcs x.v2, x.hi1, xzr
  adcs x.v3, x.lo3, xzr
  adc  x.v4, x.hi3, xzr
  adds x.T1,   x.T1,   x.lo0
  adcs x.T2, x.T2, x.v1
  adcs x.T3, x.T3, x.v2
  adcs x.T4, x.T4, x.v3
  adcs x.T5, x.T5, x.v4
  adcs  x.T6, x.T6, xzr
  adcs  x.T7, x.T7, xzr
  adc  x.T8, x.T8, xzr
  // reduce word 2: u = T[2]
  mov x.u, x.T2
  ubfm x.ush, x.u, #32, #31
  ubfm x.uhi, x.u, #32, #63
  subs x.lo0, xzr, x.u
  sbc  x.hi0, x.u, xzr
  subs x.lo1, x.ush, x.u
  sbc  x.hi1, x.uhi, xzr
  subs x.Dlo, xzr, x.ush
  sbc  x.Dhi, x.u, x.uhi
  adds x.lo3, x.Dlo, x.u
  adc  x.hi3, x.Dhi, xzr
  adds x.v1, x.hi0, x.lo1
  adcs x.v2, x.hi1, xzr
  adcs x.v3, x.lo3, xzr
  adc  x.v4, x.hi3, xzr
  adds x.T2,   x.T2,   x.lo0
  adcs x.T3, x.T3, x.v1
  adcs x.T4, x.T4, x.v2
  adcs x.T5, x.T5, x.v3
  adcs x.T6, x.T6, x.v4
  adcs  x.T7, x.T7, xzr
  adc  x.T8, x.T8, xzr
  // reduce word 3: u = T[3]
  mov x.u, x.T3
  ubfm x.ush, x.u, #32, #31
  ubfm x.uhi, x.u, #32, #63
  subs x.lo0, xzr, x.u
  sbc  x.hi0, x.u, xzr
  subs x.lo1, x.ush, x.u
  sbc  x.hi1, x.uhi, xzr
  subs x.Dlo, xzr, x.ush
  sbc  x.Dhi, x.u, x.uhi
  adds x.lo3, x.Dlo, x.u
  adc  x.hi3, x.Dhi, xzr
  adds x.v1, x.hi0, x.lo1
  adcs x.v2, x.hi1, xzr
  adcs x.v3, x.lo3, xzr
  adc  x.v4, x.hi3, xzr
  adds x.T3,   x.T3,   x.lo0
  adcs x.T4, x.T4, x.v1
  adcs x.T5, x.T5, x.v2
  adcs x.T6, x.T6, x.v3
  adcs x.T7, x.T7, x.v4
  adc  x.T8, x.T8, xzr
  // ---- result = T4..T7 (overflow T8); conditional subtract p ----
  movn x.p0, #0
  movz x.p1, #0xffff
  movk x.p1, #0xffff, lsl #16
  movz x.p3, #0x0001
  movk x.p3, #0xffff, lsl #32
  movk x.p3, #0xffff, lsl #48
  subs x.s0, x.T4, x.p0
  sbcs x.s1, x.T5, x.p1
  sbcs x.s2, x.T6, xzr
  sbcs x.s3, x.T7, x.p3
  sbcs xzr,  x.T8, xzr
  csel x.o0, x.s0, x.T4, cs
  csel x.o1, x.s1, x.T5, cs
  csel x.o2, x.s2, x.T6, cs
  csel x.o3, x.s3, x.T7, cs
  str x.o0, [x.r, #0]
  str x.o1, [x.r, #8]
  str x.o2, [x.r, #16]
  str x.o3, [x.r, #24]
  ret
.end
