.function bn_mul_mont_op16 export (
  in: x.r, x.a, x.b, x.m, x.n0
)
entry:
  .save all
  mov x.acc0, xzr
  mov x.acc1, xzr
  mov x.acc2, xzr
  mov x.acc3, xzr
  mov x.acc4, xzr
  mov x.acc5, xzr
  mov x.acc6, xzr
  mov x.acc7, xzr
  mov x.acc8, xzr
  mov x.acc9, xzr
  mov x.acc10, xzr
  mov x.acc11, xzr
  mov x.acc12, xzr
  mov x.acc13, xzr
  mov x.acc14, xzr
  mov x.acc15, xzr
  mov x.acc16, xzr
  mov x.acc17, xzr
  // b[0] base=0
  ldr x.bi, [x.b, #0]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  adcs x.acc16, x.acc16, xzr
  adc  x.acc17, x.acc17, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  adc  x.acc17, x.acc17, xzr
  mul x.mi, x.acc0, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  adcs x.acc16, x.acc16, xzr
  adc  x.acc17, x.acc17, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  adc  x.acc17, x.acc17, xzr
  mov x.acc0, xzr
  // b[1] base=1
  ldr x.bi, [x.b, #8]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  adcs x.acc17, x.acc17, xzr
  adc  x.acc0, x.acc0, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  adc  x.acc0, x.acc0, xzr
  mul x.mi, x.acc1, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  adcs x.acc17, x.acc17, xzr
  adc  x.acc0, x.acc0, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  adc  x.acc0, x.acc0, xzr
  mov x.acc1, xzr
  // b[2] base=2
  ldr x.bi, [x.b, #16]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  adcs x.acc0, x.acc0, xzr
  adc  x.acc1, x.acc1, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  adc  x.acc1, x.acc1, xzr
  mul x.mi, x.acc2, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  adcs x.acc0, x.acc0, xzr
  adc  x.acc1, x.acc1, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  adc  x.acc1, x.acc1, xzr
  mov x.acc2, xzr
  // b[3] base=3
  ldr x.bi, [x.b, #24]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  adcs x.acc1, x.acc1, xzr
  adc  x.acc2, x.acc2, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  adc  x.acc2, x.acc2, xzr
  mul x.mi, x.acc3, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  adcs x.acc1, x.acc1, xzr
  adc  x.acc2, x.acc2, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  adc  x.acc2, x.acc2, xzr
  mov x.acc3, xzr
  // b[4] base=4
  ldr x.bi, [x.b, #32]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  adcs x.acc2, x.acc2, xzr
  adc  x.acc3, x.acc3, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  adc  x.acc3, x.acc3, xzr
  mul x.mi, x.acc4, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  adcs x.acc2, x.acc2, xzr
  adc  x.acc3, x.acc3, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  adc  x.acc3, x.acc3, xzr
  mov x.acc4, xzr
  // b[5] base=5
  ldr x.bi, [x.b, #40]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  adcs x.acc3, x.acc3, xzr
  adc  x.acc4, x.acc4, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  adc  x.acc4, x.acc4, xzr
  mul x.mi, x.acc5, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  adcs x.acc3, x.acc3, xzr
  adc  x.acc4, x.acc4, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  adc  x.acc4, x.acc4, xzr
  mov x.acc5, xzr
  // b[6] base=6
  ldr x.bi, [x.b, #48]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  adc  x.acc5, x.acc5, xzr
  mul x.mi, x.acc6, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  adcs x.acc4, x.acc4, xzr
  adc  x.acc5, x.acc5, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  adc  x.acc5, x.acc5, xzr
  mov x.acc6, xzr
  // b[7] base=7
  ldr x.bi, [x.b, #56]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  adcs x.acc5, x.acc5, xzr
  adc  x.acc6, x.acc6, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  adc  x.acc6, x.acc6, xzr
  mul x.mi, x.acc7, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  adcs x.acc5, x.acc5, xzr
  adc  x.acc6, x.acc6, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  adc  x.acc6, x.acc6, xzr
  mov x.acc7, xzr
  // b[8] base=8
  ldr x.bi, [x.b, #64]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  adcs x.acc6, x.acc6, xzr
  adc  x.acc7, x.acc7, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  adc  x.acc7, x.acc7, xzr
  mul x.mi, x.acc8, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  adcs x.acc6, x.acc6, xzr
  adc  x.acc7, x.acc7, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  adc  x.acc7, x.acc7, xzr
  mov x.acc8, xzr
  // b[9] base=9
  ldr x.bi, [x.b, #72]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  adcs x.acc7, x.acc7, xzr
  adc  x.acc8, x.acc8, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  adc  x.acc8, x.acc8, xzr
  mul x.mi, x.acc9, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  adcs x.acc7, x.acc7, xzr
  adc  x.acc8, x.acc8, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  adc  x.acc8, x.acc8, xzr
  mov x.acc9, xzr
  // b[10] base=10
  ldr x.bi, [x.b, #80]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  adcs x.acc8, x.acc8, xzr
  adc  x.acc9, x.acc9, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  adc  x.acc9, x.acc9, xzr
  mul x.mi, x.acc10, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  adcs x.acc8, x.acc8, xzr
  adc  x.acc9, x.acc9, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  adc  x.acc9, x.acc9, xzr
  mov x.acc10, xzr
  // b[11] base=11
  ldr x.bi, [x.b, #88]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  adcs x.acc9, x.acc9, xzr
  adc  x.acc10, x.acc10, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  adc  x.acc10, x.acc10, xzr
  mul x.mi, x.acc11, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  adcs x.acc9, x.acc9, xzr
  adc  x.acc10, x.acc10, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  adc  x.acc10, x.acc10, xzr
  mov x.acc11, xzr
  // b[12] base=12
  ldr x.bi, [x.b, #96]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  adcs x.acc10, x.acc10, xzr
  adc  x.acc11, x.acc11, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  adc  x.acc11, x.acc11, xzr
  mul x.mi, x.acc12, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  adcs x.acc10, x.acc10, xzr
  adc  x.acc11, x.acc11, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  adc  x.acc11, x.acc11, xzr
  mov x.acc12, xzr
  // b[13] base=13
  ldr x.bi, [x.b, #104]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc13, x.acc13, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  adcs x.acc11, x.acc11, xzr
  adc  x.acc12, x.acc12, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  adc  x.acc12, x.acc12, xzr
  mul x.mi, x.acc13, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc13, x.acc13, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  adcs x.acc11, x.acc11, xzr
  adc  x.acc12, x.acc12, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  adc  x.acc12, x.acc12, xzr
  mov x.acc13, xzr
  // b[14] base=14
  ldr x.bi, [x.b, #112]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc14, x.acc14, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  adcs x.acc12, x.acc12, xzr
  adc  x.acc13, x.acc13, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  adc  x.acc13, x.acc13, xzr
  mul x.mi, x.acc14, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc14, x.acc14, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  adcs x.acc12, x.acc12, xzr
  adc  x.acc13, x.acc13, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  adc  x.acc13, x.acc13, xzr
  mov x.acc14, xzr
  // b[15] base=15
  ldr x.bi, [x.b, #120]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc15, x.acc15, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #48]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #56]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #64]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #72]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #80]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #88]
  mul x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #96]
  mul x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #104]
  mul x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #112]
  mul x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #120]
  mul x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  adcs x.acc13, x.acc13, xzr
  adc  x.acc14, x.acc14, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc16, x.acc16, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #48]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #56]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #64]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #72]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #80]
  umulh x.p, x.t, x.bi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.a, #88]
  umulh x.p, x.t, x.bi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.a, #96]
  umulh x.p, x.t, x.bi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.a, #104]
  umulh x.p, x.t, x.bi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.a, #112]
  umulh x.p, x.t, x.bi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.a, #120]
  umulh x.p, x.t, x.bi
  adcs x.acc13, x.acc13, x.p
  adc  x.acc14, x.acc14, xzr
  mul x.mi, x.acc15, x.n0
  ldr x.t, [x.m, #0]
  mul x.p, x.t, x.mi
  adds x.acc15, x.acc15, x.p
  ldr x.t, [x.m, #8]
  mul x.p, x.t, x.mi
  adcs x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #16]
  mul x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #24]
  mul x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #32]
  mul x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #40]
  mul x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #48]
  mul x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #56]
  mul x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #64]
  mul x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #72]
  mul x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #80]
  mul x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #88]
  mul x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #96]
  mul x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #104]
  mul x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #112]
  mul x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #120]
  mul x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  adcs x.acc13, x.acc13, xzr
  adc  x.acc14, x.acc14, xzr
  ldr x.t, [x.m, #0]
  umulh x.p, x.t, x.mi
  adds x.acc16, x.acc16, x.p
  ldr x.t, [x.m, #8]
  umulh x.p, x.t, x.mi
  adcs x.acc17, x.acc17, x.p
  ldr x.t, [x.m, #16]
  umulh x.p, x.t, x.mi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.m, #24]
  umulh x.p, x.t, x.mi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.m, #32]
  umulh x.p, x.t, x.mi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.m, #40]
  umulh x.p, x.t, x.mi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.m, #48]
  umulh x.p, x.t, x.mi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.m, #56]
  umulh x.p, x.t, x.mi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.m, #64]
  umulh x.p, x.t, x.mi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.m, #72]
  umulh x.p, x.t, x.mi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.m, #80]
  umulh x.p, x.t, x.mi
  adcs x.acc8, x.acc8, x.p
  ldr x.t, [x.m, #88]
  umulh x.p, x.t, x.mi
  adcs x.acc9, x.acc9, x.p
  ldr x.t, [x.m, #96]
  umulh x.p, x.t, x.mi
  adcs x.acc10, x.acc10, x.p
  ldr x.t, [x.m, #104]
  umulh x.p, x.t, x.mi
  adcs x.acc11, x.acc11, x.p
  ldr x.t, [x.m, #112]
  umulh x.p, x.t, x.mi
  adcs x.acc12, x.acc12, x.p
  ldr x.t, [x.m, #120]
  umulh x.p, x.t, x.mi
  adcs x.acc13, x.acc13, x.p
  adc  x.acc14, x.acc14, xzr
  mov x.acc15, xzr
  ldr x.t, [x.m, #0]
  subs x.s0, x.acc16, x.t
  ldr x.t, [x.m, #8]
  sbcs x.s1, x.acc17, x.t
  ldr x.t, [x.m, #16]
  sbcs x.s2, x.acc0, x.t
  ldr x.t, [x.m, #24]
  sbcs x.s3, x.acc1, x.t
  ldr x.t, [x.m, #32]
  sbcs x.s4, x.acc2, x.t
  ldr x.t, [x.m, #40]
  sbcs x.s5, x.acc3, x.t
  ldr x.t, [x.m, #48]
  sbcs x.s6, x.acc4, x.t
  ldr x.t, [x.m, #56]
  sbcs x.s7, x.acc5, x.t
  ldr x.t, [x.m, #64]
  sbcs x.s8, x.acc6, x.t
  ldr x.t, [x.m, #72]
  sbcs x.s9, x.acc7, x.t
  ldr x.t, [x.m, #80]
  sbcs x.s10, x.acc8, x.t
  ldr x.t, [x.m, #88]
  sbcs x.s11, x.acc9, x.t
  ldr x.t, [x.m, #96]
  sbcs x.s12, x.acc10, x.t
  ldr x.t, [x.m, #104]
  sbcs x.s13, x.acc11, x.t
  ldr x.t, [x.m, #112]
  sbcs x.s14, x.acc12, x.t
  ldr x.t, [x.m, #120]
  sbcs x.s15, x.acc13, x.t
  sbcs xzr, x.acc14, xzr
  csel x.o0, x.s0, x.acc16, cs
  csel x.o1, x.s1, x.acc17, cs
  csel x.o2, x.s2, x.acc0, cs
  csel x.o3, x.s3, x.acc1, cs
  csel x.o4, x.s4, x.acc2, cs
  csel x.o5, x.s5, x.acc3, cs
  csel x.o6, x.s6, x.acc4, cs
  csel x.o7, x.s7, x.acc5, cs
  csel x.o8, x.s8, x.acc6, cs
  csel x.o9, x.s9, x.acc7, cs
  csel x.o10, x.s10, x.acc8, cs
  csel x.o11, x.s11, x.acc9, cs
  csel x.o12, x.s12, x.acc10, cs
  csel x.o13, x.s13, x.acc11, cs
  csel x.o14, x.s14, x.acc12, cs
  csel x.o15, x.s15, x.acc13, cs
  str x.o0, [x.r, #0]
  str x.o1, [x.r, #8]
  str x.o2, [x.r, #16]
  str x.o3, [x.r, #24]
  str x.o4, [x.r, #32]
  str x.o5, [x.r, #40]
  str x.o6, [x.r, #48]
  str x.o7, [x.r, #56]
  str x.o8, [x.r, #64]
  str x.o9, [x.r, #72]
  str x.o10, [x.r, #80]
  str x.o11, [x.r, #88]
  str x.o12, [x.r, #96]
  str x.o13, [x.r, #104]
  str x.o14, [x.r, #112]
  str x.o15, [x.r, #120]
  .restore all
  ret
.end
