// GENERATED by gen_montmul_p256_cios.py -- do not edit by hand.
// Interleaved CIOS Montgomery multiply mod P-256 prime. ABI: x0=r,x1=a,x2=b.
.function mont_mul_p256 export (
  in: x.r, x.a, x.b
)
entry:
  ldr x.a0, [x.a, #0]
  ldr x.a1, [x.a, #8]
  ldr x.a2, [x.a, #16]
  ldr x.a3, [x.a, #24]
  ldr x.b0, [x.b, #0]
  ldr x.b1, [x.b, #8]
  ldr x.b2, [x.b, #16]
  ldr x.b3, [x.b, #24]
  // b[0]
  mul   x.acc0, x.a0, x.b0
  umulh x.t0,   x.a0, x.b0
  mul   x.acc1, x.a1, x.b0
  umulh x.t1,   x.a1, x.b0
  mul   x.acc2, x.a2, x.b0
  umulh x.t2,   x.a2, x.b0
  mul   x.acc3, x.a3, x.b0
  umulh x.t3,   x.a3, x.b0
  adds  x.acc1, x.acc1, x.t0
  adcs  x.acc2, x.acc2, x.t1
  adcs  x.acc3, x.acc3, x.t2
  adc   x.acc4, xzr, x.t3
  mov   x.acc5, xzr
  ubfm x.t0, x.acc0, #32, #31
  ubfm x.t1, x.acc0, #32, #63
  subs x.t2, x.acc0, x.t0
  sbc  x.t3, x.acc0, x.t1
  adds x.acc0, x.acc1, x.t0
  adcs x.acc1, x.acc2, x.t1
  adcs x.acc2, x.acc3, x.t2
  adcs x.acc3, x.acc4, x.t3
  adc  x.acc4, x.acc5, xzr
  // b[1]
  mul x.t0, x.a0, x.b1
  mul x.t1, x.a1, x.b1
  mul x.t2, x.a2, x.b1
  mul x.t3, x.a3, x.b1
  adds x.acc0, x.acc0, x.t0
  adcs x.acc1, x.acc1, x.t1
  adcs x.acc2, x.acc2, x.t2
  adcs x.acc3, x.acc3, x.t3
  adc  x.acc4, x.acc4, xzr
  umulh x.t0, x.a0, x.b1
  umulh x.t1, x.a1, x.b1
  umulh x.t2, x.a2, x.b1
  umulh x.t3, x.a3, x.b1
  adds x.acc1, x.acc1, x.t0
  adcs x.acc2, x.acc2, x.t1
  adcs x.acc3, x.acc3, x.t2
  adcs x.acc4, x.acc4, x.t3
  adc  x.acc5, xzr, xzr
  ubfm x.t0, x.acc0, #32, #31
  ubfm x.t1, x.acc0, #32, #63
  subs x.t2, x.acc0, x.t0
  sbc  x.t3, x.acc0, x.t1
  adds x.acc0, x.acc1, x.t0
  adcs x.acc1, x.acc2, x.t1
  adcs x.acc2, x.acc3, x.t2
  adcs x.acc3, x.acc4, x.t3
  adc  x.acc4, x.acc5, xzr
  // b[2]
  mul x.t0, x.a0, x.b2
  mul x.t1, x.a1, x.b2
  mul x.t2, x.a2, x.b2
  mul x.t3, x.a3, x.b2
  adds x.acc0, x.acc0, x.t0
  adcs x.acc1, x.acc1, x.t1
  adcs x.acc2, x.acc2, x.t2
  adcs x.acc3, x.acc3, x.t3
  adc  x.acc4, x.acc4, xzr
  umulh x.t0, x.a0, x.b2
  umulh x.t1, x.a1, x.b2
  umulh x.t2, x.a2, x.b2
  umulh x.t3, x.a3, x.b2
  adds x.acc1, x.acc1, x.t0
  adcs x.acc2, x.acc2, x.t1
  adcs x.acc3, x.acc3, x.t2
  adcs x.acc4, x.acc4, x.t3
  adc  x.acc5, xzr, xzr
  ubfm x.t0, x.acc0, #32, #31
  ubfm x.t1, x.acc0, #32, #63
  subs x.t2, x.acc0, x.t0
  sbc  x.t3, x.acc0, x.t1
  adds x.acc0, x.acc1, x.t0
  adcs x.acc1, x.acc2, x.t1
  adcs x.acc2, x.acc3, x.t2
  adcs x.acc3, x.acc4, x.t3
  adc  x.acc4, x.acc5, xzr
  // b[3]
  mul x.t0, x.a0, x.b3
  mul x.t1, x.a1, x.b3
  mul x.t2, x.a2, x.b3
  mul x.t3, x.a3, x.b3
  adds x.acc0, x.acc0, x.t0
  adcs x.acc1, x.acc1, x.t1
  adcs x.acc2, x.acc2, x.t2
  adcs x.acc3, x.acc3, x.t3
  adc  x.acc4, x.acc4, xzr
  umulh x.t0, x.a0, x.b3
  umulh x.t1, x.a1, x.b3
  umulh x.t2, x.a2, x.b3
  umulh x.t3, x.a3, x.b3
  adds x.acc1, x.acc1, x.t0
  adcs x.acc2, x.acc2, x.t1
  adcs x.acc3, x.acc3, x.t2
  adcs x.acc4, x.acc4, x.t3
  adc  x.acc5, xzr, xzr
  ubfm x.t0, x.acc0, #32, #31
  ubfm x.t1, x.acc0, #32, #63
  subs x.t2, x.acc0, x.t0
  sbc  x.t3, x.acc0, x.t1
  adds x.acc0, x.acc1, x.t0
  adcs x.acc1, x.acc2, x.t1
  adcs x.acc2, x.acc3, x.t2
  adcs x.acc3, x.acc4, x.t3
  adc  x.acc4, x.acc5, xzr
  movn x.pp0, #0
  movz x.pp1, #0xffff
  movk x.pp1, #0xffff, lsl #16
  movz x.pp3, #0x0001
  movk x.pp3, #0xffff, lsl #32
  movk x.pp3, #0xffff, lsl #48
  subs x.s0, x.acc0, x.pp0
  sbcs x.s1, x.acc1, x.pp1
  sbcs x.s2, x.acc2, xzr
  sbcs x.s3, x.acc3, x.pp3
  sbcs xzr,  x.acc4, xzr
  csel x.o0, x.s0, x.acc0, cs
  csel x.o1, x.s1, x.acc1, cs
  csel x.o2, x.s2, x.acc2, cs
  csel x.o3, x.s3, x.acc3, cs
  str x.o0, [x.r, #0]
  str x.o1, [x.r, #8]
  str x.o2, [x.r, #16]
  str x.o3, [x.r, #24]
  ret
.end
