.function mul_plain6 export (
  in: x.r, x.a, x.b
)
entry:
  .save all
  mov x.acc0, xzr
  mov x.acc1, xzr
  mov x.acc2, xzr
  mov x.acc3, xzr
  mov x.acc4, xzr
  mov x.acc5, xzr
  mov x.acc6, xzr
  mov x.acc7, xzr
  // b[0] base=0
  ldr x.bi, [x.b, #0]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  adcs x.acc6, x.acc6, xzr
  adc  x.acc7, x.acc7, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  adc  x.acc7, x.acc7, xzr
  str x.acc0, [x.r, #0]
  mov x.acc0, xzr
  // b[1] base=1
  ldr x.bi, [x.b, #8]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  adcs x.acc7, x.acc7, xzr
  adc  x.acc0, x.acc0, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  adc  x.acc0, x.acc0, xzr
  str x.acc1, [x.r, #8]
  mov x.acc1, xzr
  // b[2] base=2
  ldr x.bi, [x.b, #16]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  adcs x.acc0, x.acc0, xzr
  adc  x.acc1, x.acc1, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  adc  x.acc1, x.acc1, xzr
  str x.acc2, [x.r, #16]
  mov x.acc2, xzr
  // b[3] base=3
  ldr x.bi, [x.b, #24]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc3, x.acc3, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  adcs x.acc1, x.acc1, xzr
  adc  x.acc2, x.acc2, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  adc  x.acc2, x.acc2, xzr
  str x.acc3, [x.r, #24]
  mov x.acc3, xzr
  // b[4] base=4
  ldr x.bi, [x.b, #32]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc4, x.acc4, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  adcs x.acc2, x.acc2, xzr
  adc  x.acc3, x.acc3, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  adc  x.acc3, x.acc3, xzr
  str x.acc4, [x.r, #32]
  mov x.acc4, xzr
  // b[5] base=5
  ldr x.bi, [x.b, #40]
  ldr x.t, [x.a, #0]
  mul x.p, x.t, x.bi
  adds x.acc5, x.acc5, x.p
  ldr x.t, [x.a, #8]
  mul x.p, x.t, x.bi
  adcs x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #16]
  mul x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #24]
  mul x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #32]
  mul x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #40]
  mul x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  adcs x.acc3, x.acc3, xzr
  adc  x.acc4, x.acc4, xzr
  ldr x.t, [x.a, #0]
  umulh x.p, x.t, x.bi
  adds x.acc6, x.acc6, x.p
  ldr x.t, [x.a, #8]
  umulh x.p, x.t, x.bi
  adcs x.acc7, x.acc7, x.p
  ldr x.t, [x.a, #16]
  umulh x.p, x.t, x.bi
  adcs x.acc0, x.acc0, x.p
  ldr x.t, [x.a, #24]
  umulh x.p, x.t, x.bi
  adcs x.acc1, x.acc1, x.p
  ldr x.t, [x.a, #32]
  umulh x.p, x.t, x.bi
  adcs x.acc2, x.acc2, x.p
  ldr x.t, [x.a, #40]
  umulh x.p, x.t, x.bi
  adcs x.acc3, x.acc3, x.p
  adc  x.acc4, x.acc4, xzr
  str x.acc5, [x.r, #40]
  mov x.acc5, xzr
  str x.acc6, [x.r, #48]
  str x.acc7, [x.r, #56]
  str x.acc0, [x.r, #64]
  str x.acc1, [x.r, #72]
  str x.acc2, [x.r, #80]
  str x.acc3, [x.r, #88]
  .restore all
  ret
.end
